# -*- coding: utf-8 -*-
# 追加 500 个雅思核心词到 ielts/ielts_bank.json
# 字段：[word, ipa, pos_cn, story(记忆法), tip(用法), en(例句), cn(例句译)]
# 去重：若 word 已存在于词库则跳过。
import io, json, os

HERE = os.path.dirname(os.path.abspath(__file__))
BANK = os.path.abspath(os.path.join(HERE, "..", "ielts", "ielts_bank.json"))

NEW_WORDS = [
["abandon", "/əˈbændən/", "v. 抛弃，放弃", "a+band(乐队)+on：乐队散了→抛弃", "abandon doing / abandoned adj.", "They abandoned the sinking ship.", "他们弃船而逃。"],
["abstract", "/ˈæbstrækt/", "adj. 抽象的", "abs(离开)+tract(拉)：抽离出来→抽象", "反义 concrete 具体的", "The idea is too abstract.", "这个想法太抽象了。"],
["accelerate", "/əkˈseləreɪt/", "v. 加速", "ac+celer(快)+ate", "accelerate the process", "The car accelerated quickly.", "汽车迅速加速。"],
["accommodate", "/əˈkɒmədeɪt/", "v. 容纳；适应", "ac+com(共同)+mod(量)+ate：调到合适", "accommodate to / accommodate guests", "The hall accommodates 500 people.", "大厅可容纳500人。"],
["accompany", "/əˈkʌmpəni/", "v. 陪伴；伴随", "ac+company(同伴)", "accompany sb", "She accompanied her friend.", "她陪着朋友。"],
["accurate", "/ˈækjərət/", "adj. 精确的", "ac+cur(关心)+ate：用心→准", "accurate data / inaccurate", "The report is accurate.", "报告很准确。"],
["achieve", "/əˈtʃiːv/", "v. 实现，达成", "a+chieve(-chief)：做到头", "achieve one's goal", "He achieved great success.", "他取得了巨大成功。"],
["acquire", "/əˈkwaɪə/", "v. 获得，习得", "ac+quire(寻求)", "acquire knowledge/skills", "Babies acquire language fast.", "婴儿学语言很快。"],
["adapt", "/əˈdæpt/", "v. 适应；改编", "ad+apt(适合)", "adapt to / adapt for", "Plants adapt to the climate.", "植物适应气候。"],
["adequate", "/ˈædɪkwət/", "adj. 足够的", "ad+eat：能吃下就够", "反义 inadequate", "We have adequate food.", "我们有足够的食物。"],
["adjacent", "/əˈdʒeɪsənt/", "adj. 相邻的", "ad+jac(躺)+ent：躺旁边", "adjacent to", "The two buildings are adjacent.", "两栋楼相邻。"],
["adjust", "/əˈdʒʌst/", "v. 调整，适应", "ad+just(正)：调正", "adjust to / adjust the settings", "He adjusted to the new job.", "他适应了新工作。"],
["administer", "/ədˈmɪnɪstə/", "v. 管理；执行", "ad+minister(部长)：像部长管事", "administer a test / a country", "She administers the project.", "她管理这个项目。"],
["adolescent", "/ˌædəˈlesnt/", "n./adj. 青少年(的)", "ad+olesc(长大)+ent", "adolescent students", "Adolescents need guidance.", "青少年需要引导。"],
["advance", "/ədˈvɑːns/", "v./n. 推进，进步", "ad+van(前)+ce：向前", "in advance / advance technology", "Science has advanced rapidly.", "科学飞速进步。"],
["adverse", "/ədˈvɜːs/", "adj. 不利的", "ad+vers(转)+e：转向坏", "adverse effect / weather", "The drug had adverse effects.", "这药有副作用。"],
["advocate", "/ˈædvəkeɪt/", "v. 提倡；n. 拥护者", "ad+voc(声)+ate：发声支持", "advocate for / an advocate of", "He advocates free speech.", "他提倡言论自由。"],
["affect", "/əˈfekt/", "v. 影响", "af+fect(做)：施加作用", "易混 affect(v.影响) vs effect(n.效果)", "Climate affects crops.", "气候影响庄稼。"],
["afford", "/əˈfɔːd/", "v. 负担得起", "af+ford(向前)：拿得出", "can/cannot afford", "We cannot afford a car.", "我们买不起车。"],
["aggregate", "/ˈæɡrɪɡət/", "v./n. 合计，聚集", "ag+greg(群)+ate：成群", "in the aggregate", "The aggregate score is 12.", "总分是12分。"],
["aggressive", "/əˈɡresɪv/", "adj. 好斗的；积极的", "ag+gress(走)+ive：向前冲", "aggressive marketing", "They took an aggressive approach.", "他们采取了激进策略。"],
["allocate", "/ˈæləkeɪt/", "v. 分配", "al+locate(放置)：放到各处", "allocate funds/time to", "We allocated money to schools.", "我们给学校拨了款。"],
["ambiguous", "/æmˈbɪɡjuəs/", "adj. 模糊的，含糊的", "ambi(两)+iguous：两义", "反义 clear/unambiguous", "His answer was ambiguous.", "他的回答含糊其辞。"],
["ambitious", "/æmˈbɪʃəs/", "adj. 有雄心的", "ambit(环绕)+ious：想包围更多", "an ambitious plan", "She has ambitious goals.", "她目标远大。"],
["analogous", "/əˈnæləɡəs/", "adj. 类似的", "ana(类似)+log(说)+ous", "analogous to", "This is analogous to that.", "这与那个类似。"],
["analyse", "/ˈænəlaɪz/", "v. 分析", "ana(贯穿)+lyse(松)：拆开看", "analyse the data", "We analysed the results.", "我们分析了结果。"],
["ancient", "/ˈeɪnʃənt/", "adj. 古代的", "anci(老)+ent", "ancient history", "They studied ancient Rome.", "他们研究古罗马。"],
["announce", "/əˈnaʊns/", "v. 宣布", "an+nounce(告知)", "announce a decision", "They announced the winner.", "他们宣布了获胜者。"],
["anonymous", "/əˈnɒnɪməs/", "adj. 匿名的", "an(无)+onym(名)+ous", "an anonymous letter", "He sent an anonymous email.", "他发了一封匿名邮件。"],
["anticipate", "/ænˈtɪsɪpeɪt/", "v. 预期，预料", "anti(前)+cip(拿)：提前拿", "= expect，更正式", "We anticipate delays.", "我们预计会延误。"],
["anxiety", "/æŋˈzaɪəti/", "n. 焦虑", "anx(窄)+iety：心发紧", "feel anxiety", "Exam anxiety is common.", "考前焦虑很常见。"],
["apparent", "/əˈpærənt/", "adj. 明显的", "ap+parent(明显的)", "it is apparent that...", "It is apparent he lied.", "显然他说了谎。"],
["appeal", "/əˈpiːl/", "v./n. 呼吁；吸引", "ap+peal(推)：推向人", "appeal to / appeal for", "The idea appeals to me.", "这个想法吸引我。"],
["applaud", "/əˈplɔːd/", "v. 鼓掌；称赞", "ap+plaud(拍)", "applaud the effort", "The audience applauded.", "观众鼓掌。"],
["applicable", "/əˈplɪkəbl/", "adj. 适用的", "ap+plic(折)+able：可贴合", "applicable to", "The rule is applicable.", "这规则适用。"],
["appreciate", "/əˈpriːʃieɪt/", "v. 欣赏；感激", "ap+preci(价值)+ate：看重", "I appreciate your help.", "我感激你的帮助。"],
["approach", "/əˈprəʊtʃ/", "v./n. 接近；方法", "ap+proach(近)", "approach a problem", "We need a new approach.", "我们需要新方法。"],
["appropriate", "/əˈprəʊpriət/", "adj. 合适的", "ap+propri(适当)+ate", "反义 inappropriate", "Wear appropriate clothes.", "穿合适的衣服。"],
["approximate", "/əˈprɒksɪmət/", "adj./v. 近似的", "ap+proxim(近)+ate", "approximately = 大约", "The cost is approximate.", "花费是大概的数。"],
["arbitrary", "/ˈɑːbɪtrəri/", "adj. 武断的，随意的", "arbit(判断)+ary：凭己判", "反义 reasonable", "The choice seemed arbitrary.", "这个选择显得武断。"],
["argue", "/ˈɑːɡjuː/", "v. 争论；主张", "arg(亮)+ue", "argue that / argue for", "He argued for change.", "他主张变革。"],
["arise", "/əˈraɪz/", "v. 出现，产生", "a+rise(起)", "problems arise", "New problems arose.", "新问题出现了。"],
["articulate", "/ɑːˈtɪkjuleɪt/", "v. 清晰表达", "article(文)+ate：说条理", "形容词读音 /ɑːˈtɪkjələt/", "She articulated her view.", "她清晰表达了观点。"],
["artificial", "/ˌɑːtɪˈfɪʃl/", "adj. 人造的", "art(技艺)+fic(做)+ial", "artificial intelligence", "AI is artificial intelligence.", "AI 即人工智能。"],
["aspect", "/ˈæspekt/", "n. 方面", "a+spect(看)：看的角度", "every aspect of", "Consider all aspects.", "考虑所有方面。"],
["assemble", "/əˈsembl/", "v. 集合；装配", "as+semble(同)：聚到一起", "assemble a team", "They assembled the car.", "他们装配了汽车。"],
["assert", "/əˈsɜːt/", "v. 断言，坚持", "as+sert(加入)：强硬加入", "assert one's rights", "He asserted his opinion.", "他坚持己见。"],
["assess", "/əˈses/", "v. 评估", "as(加强)+sess(坐)：细看", "assess the risk", "We must assess the damage.", "我们必须评估损失。"],
["assign", "/əˈsaɪn/", "v. 分配；指派", "as+sign(标记)", "assign a task", "The teacher assigned homework.", "老师布置了作业。"],
["assist", "/əˈsɪst/", "v. 协助", "as+sist(站)：站旁边", "assist sb with", "She assisted the elderly.", "她帮助了老人。"],
["assume", "/əˈsjuːm/", "v. 假定；承担", "as+sume(拿)：先拿前提", "assume (that)...", "I assume he is right.", "我假定他是对的。"],
["assure", "/əˈʃʊə/", "v. 保证", "as+sure(确实)", "assure sb that", "He assured me of safety.", "他向我保证安全。"],
["attach", "/əˈtætʃ/", "v. 附上；依恋", "at+tach(钉)：钉上", "attach a file", "Please attach the photo.", "请附上照片。"],
["attain", "/əˈteɪn/", "v. 达到，获得", "at+tain(触)：触到", "attain a goal", "He attained his dream.", "他实现了梦想。"],
["attitude", "/ˈætɪtjuːd/", "n. 态度", "atti(适合)+tude", "a positive attitude", "Attitude decides everything.", "态度决定一切。"],
["attribute", "/əˈtrɪbjuːt/", "v. 归因于", "at+tribute(赋予)", "attribute A to B", "He attributed success to luck.", "他把成功归于运气。"],
["authority", "/ɔːˈθɒrəti/", "n. 权威；当局", "author(作者)+ity：说话算数", "in authority", "The authority banned it.", "当局禁止了它。"],
["automatic", "/ˌɔːtəˈmætɪk/", "adj. 自动的", "auto(自)+matic", "automatic door", "The process is automatic.", "流程是自动的。"],
["available", "/əˈveɪləbl/", "adj. 可用的", "a+vail(用)+able", "available to / available now", "Tickets are available.", "票还有。"],
["average", "/ˈævərɪdʒ/", "n./adj. 平均(的)", "aver(避免极端)+age", "on average", "On average it takes a day.", "平均要花一天。"],
["aware", "/əˈweə/", "adj. 意识到的", "a+ware(注意)", "be aware of", "Be aware of the risk.", "注意风险。"],
["awkward", "/ˈɔːkwəd/", "adj. 笨拙的；尴尬的", "awk(反手)+ward", "an awkward silence", "There was an awkward pause.", "出现一阵尴尬的沉默。"],
["bais", "/ˈbeɪs/", "n. 偏见；v. 使偏向", "bias 音似‘偏好’", "cognitive bias", "The test shows a bias.", "测试显示出偏见。"],
["barrier", "/ˈbæriə/", "n. 障碍", "barr(栏)+ier", "language barrier", "The wall is a barrier.", "这墙是个障碍。"],
["behalf", "/bɪˈhɑːf/", "n. 代表；利益", "be+list(列)：列名下", "on behalf of", "I speak on his behalf.", "我代表他发言。"],
["behave", "/bɪˈheɪv/", "v. 表现；举止", "be+have(有)：有样", "behave well", "Children should behave.", "孩子应有礼貌。"],
["believe", "/bɪˈliːv/", "v. 相信", "be+lieve(爱)", "believe in / believe that", "I believe he is honest.", "我相信他是诚实的。"],
["benefit", "/ˈbenɪfɪt/", "n. 益处；v. 受益", "bene(好)+fit", "benefit from", "We benefit from exercise.", "我们受益于运动。"],
["bias", "/ˈbaɪəs/", "n. 偏见", "bias 音似‘偏好’", "cognitive bias 认知偏差", "The report shows a bias.", "报告有明显偏见。"],
["boost", "/buːst/", "v./n. 提升，推动", "boost 音似‘补斯特’", "boost morale", "The ad boosted sales.", "广告提振了销量。"],
["bound", "/baʊnd/", "adj. 必定的；受约束的", "bound 音似‘绑的’", "be bound to", "He is bound to succeed.", "他必定会成功。"],
["breif", "/briːf/", "adj. 简短的", "breif 音似‘brief’", "in brief / a brief meeting", "Give a brief summary.", "做个简短总结。"],
["broad", "/brɔːd/", "adj. 宽阔的", "broad 与‘宽’联想", "broad support", "The road is broad.", "这条路很宽。"],
["budget", "/ˈbʌdʒɪt/", "n. 预算", "budget 音似‘巴结它’", "within budget", "We are over budget.", "我们超预算了。"],
["bureau", "/ˈbjʊərəʊ/", "n. 局，办事处", "bureau 音似‘局’", "a government bureau", "The bureau issued a rule.", "该局发布了一项规定。"],
["bypass", "/ˈbaɪpɑːs/", "v. 绕过", "by+pass(过)", "bypass the problem", "They bypassed the queue.", "他们绕过了排队。"],
["capable", "/ˈkeɪpəbl/", "adj. 有能力的", "cap(抓)+able：抓得住", "capable of", "She is capable ofleading.", "她有能力领导。"],
["capacity", "/kəˈpæsəti/", "n. 容量；能力", "cap(抓)+acity", "seating capacity", "The hall has great capacity.", "大厅容量很大。"],
["category", "/ˈkætəɡəri/", "n. 类别", "cata(下)+gory(组)", "in the same category", "Sort them by category.", "按类别分类。"],
["cease", "/siːs/", "v. 停止", "cease 音似‘息司’", "cease to do", "The rain ceased.", "雨停了。"],
["challenge", "/ˈtʃælɪndʒ/", "n./v. 挑战", "challenge 音似‘差林治’", "face a challenge", "This is a real challenge.", "这是个真正的挑战。"],
["channel", "/ˈtʃænl/", "n. 渠道；频道", "channel 音似‘渠道’", "through official channels", "Use the right channel.", "用对渠道。"],
["chapter", "/ˈtʃæptə/", "n. 章节", "chapt(头)+er：一段开头", "read a chapter", "Finish this chapter.", "读完这一章。"],
["characteristic", "/ˌkærəktəˈrɪstɪk/", "n./adj. 特征(的)", "character+istic", "a key characteristic", "Honesty is a trait.", "诚实是一种特质。"],
["citizen", "/ˈsɪtɪzn/", "n. 公民", "citi(城市)+zen", "a responsible citizen", "Every citizen has duties.", "每个公民都有义务。"],
["civil", "/ˈsɪvl/", "adj. 公民的；民事的", "civil 音似‘市民’", "civil rights", "They fought for civil rights.", "他们为民权而战。"],
["clarify", "/ˈklærɪfaɪ/", "v. 澄清", "clar(清)+ify(使)", "clarify the point", "Let me clarify my view.", "让我澄清观点。"],
["classic", "/ˈklæsɪk/", "adj. 经典的", "class(级)+ic", "a classic novel", "This is a classic book.", "这是一本经典书。"],
["clue", "/kluː/", "n. 线索", "clue 音似‘刻路’", "a vital clue", "The clue solved the case.", "线索破了案。"],
["coincide", "/ˌkəʊɪnˈsaɪd/", "v. 同时发生；一致", "co(共同)+incide(落)", "coincide with", "The holiday coincides with it.", "假期正好碰上。"],
["collaborate", "/kəˈlæbəreɪt/", "v. 合作", "col+labour(劳动)+ate", "collaborate with", "They collaborated on the paper.", "他们合作写了论文。"],
["collapse", "/kəˈlæps/", "v./n. 倒塌；崩溃", "col+lapse(滑)：一起滑倒", "the economy collapsed", "The bridge collapsed.", "桥塌了。"],
["colleague", "/ˈkɒliːɡ/", "n. 同事", "col+league(联盟)", "a trusted colleague", "My colleagues are helpful.", "我的同事很帮忙。"],
["commence", "/kəˈmens/", "v. 开始", "com+mence(开始)", "commence with", "The meeting commenced.", "会议开始了。"],
["comment", "/ˈkɒment/", "n./v. 评论", "com+ment(心)：说心里话", "comment on", "She commented on the news.", "她评论了这则新闻。"],
["commission", "/kəˈmɪʃn/", "n. 委员会；佣金", "com+miss(派)+ion", "a commission of inquiry", "The commission investigated.", "委员会展开了调查。"],
["commit", "/kəˈmɪt/", "v. 承诺；犯(错)", "com+mit(派)：把自己交出去", "commit to", "He committed to the plan.", "他承诺执行计划。"],
["commodity", "/kəˈmɒdəti/", "n. 商品", "com+mod(量)+ity", "a basic commodity", "Oil is a key commodity.", "石油是关键商品。"],
["compel", "/kəmˈpel/", "v. 强迫", "com+pel(推)：一起推", "be compelled to", "He was compelled to leave.", "他被迫离开。"],
["compensate", "/ˈkɒmpenseɪt/", "v. 补偿", "com+pens(钱)+ate", "compensate for", "Nothing compensates for time.", "什么也补偿不了时间。"],
["compile", "/kəmˈpaɪl/", "v. 编纂；编译", "com+pile(堆)", "compile a list", "They compiled a report.", "他们编了一份报告。"],
["complement", "/ˈkɒmplɪment/", "n./v. 补充；补足", "com+ple(满)+ment", "易混 complement vs compliment", "Wine complements food.", "酒与食物相得益彰。"],
["complex", "/ˈkɒmpleks/", "adj. 复杂的", "com+plex(折)：多折", "a complex issue", "The system is complex.", "系统很复杂。"],
["comply", "/kəmˈplaɪ/", "v. 遵从", "com+ply(满)：凑满规则", "comply with", "We comply with the law.", "我们遵守法律。"],
["component", "/kəmˈpəʊnənt/", "n. 组成部分", "com+pon(放)+ent", "a key component", "Trust is a component.", "信任是一个组成部分。"],
["comprehend", "/ˌkɒmprɪˈhend/", "v. 理解", "com+prehend(抓)：全抓", "= understand，较正式", "I cannot comprehend it.", "我无法理解它。"],
["comprise", "/kəmˈpraɪz/", "v. 包含；由…组成", "com+prise(抓)：全抓在里", "be comprised of", "The team comprises 10.", "团队由10人组成。"],
["conceive", "/kənˈsiːv/", "v. 构想；怀孕", "con+ceive(拿)：心里拿主意", "conceive of / an idea", "She conceived a plan.", "她想出了一个计划。"],
["concentrate", "/ˈkɒnsntreɪt/", "v. 集中；专注", "con+centr(中)+ate", "concentrate on", "Concentrate on your work.", "专心工作。"],
["concept", "/ˈkɒnsept/", "n. 概念", "con+cept(抓)：抓到的想法", "a new concept", "This is a hard concept.", "这是个难懂的概念。"],
["concern", "/kənˈsɜːn/", "v./n. 关心；担忧", "con+cern(分)：牵扯", "be concerned about", "We are concerned for him.", "我们为他担心。"],
["conclude", "/kənˈkluːd/", "v. 总结；断定", "con+clude(关)：收尾", "conclude that...", "We concluded the meeting.", "我们结束了会议。"],
["concurrent", "/kənˈkʌrənt/", "adj. 同时的", "con+current(流)", "concurrent events", "Two concurrent wars.", "两场同时的战争。"],
["condemn", "/kənˈdem/", "v. 谴责", "con+demn(判)：重判", "condemn the act", "They condemned the attack.", "他们谴责了袭击。"],
["condense", "/kənˈdens/", "v. 压缩；浓缩", "con+dense(密)", "condense the report", "Condense it into one page.", "把它压缩到一页。"],
["conduct", "/kənˈdʌkt/", "v. 实施；引导", "con+duct(引)", "conduct a study", "They conducted research.", "他们开展了研究。"],
["confer", "/kənˈfɜː/", "v. 授予；商议", "con+fer(带)：一起带", "confer a degree", "The university conferred it.", "大学授予了学位。"],
["confine", "/kənˈfaɪn/", "v. 限制；禁闭", "con+fine(终)：圈在终点内", "be confined to", "He was confined to bed.", "他卧病在床。"],
["confirm", "/kənˈfɜːm/", "v. 确认", "con+firm(坚)", "confirm the booking", "Please confirm receipt.", "请确认收到。"],
["conflict", "/ˈkɒnflɪkt/", "n./v. 冲突", "con+flict(击)：互打", "in conflict with", "Their views conflict.", "他们的观点冲突。"],
["conform", "/kənˈfɔːm/", "v. 遵守；符合", "con+form(形)：同形", "conform to", "Conform to the rules.", "遵守规则。"],
["confront", "/kənˈfrʌnt/", "v. 面对；对抗", "con+front(前)", "confront the issue", "We must confront it.", "我们必须面对它。"],
["confuse", "/kənˈfjuːz/", "v. 使困惑", "con+fuse(流)：混流", "be confused by", "Don't confuse the two.", "别把两者混淆。"],
["congress", "/ˈkɒŋɡres/", "n. 国会；大会", "con+gress(走)：走到一起", "a medical congress", "The congress met annually.", "大会每年召开。"],
["connect", "/kəˈnekt/", "v. 连接", "con+nect(绑)", "connect to", "Connect the cable.", "接上电缆。"],
["conscience", "/ˈkɒnʃəns/", "n. 良心", "con+science(知)", "a clear conscience", "He acted on conscience.", "他凭良心行事。"],
["consent", "/kənˈsent/", "n./v. 同意", "con+sent(感觉)：同感", "give one's consent", "She consented to it.", "她同意了。"],
["consequence", "/ˈkɒnsɪkwəns/", "n. 后果", "con+sequ(跟随)+ence", "as a consequence", "Pollution has consequences.", "污染有后果。"],
["conservative", "/kənˈsɜːvətɪv/", "adj. 保守的", "con+serv(保)+ative", "a conservative view", "He holds conservative views.", "他持保守观点。"],
["consider", "/kənˈsɪdə/", "v. 考虑", "con+sider(星)：细看", "consider doing", "Consider all options.", "考虑所有方案。"],
["consist", "/kənˈsɪst/", "v. 由…组成", "con+sist(站)：站在一起", "consist of", "The team consists of 5.", "团队由5人组成。"],
["console", "/kənˈsəʊl/", "v. 安慰", "con+sole(独)：同担", "console the grieving", "She consoled her friend.", "她安慰了朋友。"],
["consolidate", "/kənˈsɒlɪdeɪt/", "v. 巩固", "con+solid(固)+ate", "consolidate one's lead", "The firm consolidated power.", "公司巩固了权力。"],
["constitute", "/ˈkɒnstɪtjuːt/", "v. 构成；设立", "con+stitute(站)", "constitute a threat", "Women constitute half.", "女性占一半。"],
["constrain", "/kənˈstreɪn/", "v. 限制；约束", "con+strain(拉紧)", "constrained by time", "We are constrained by budget.", "我们受预算限制。"],
["construct", "/kənˈstrʌkt/", "v. 建造", "con+struct(建)", "construct a model", "They constructed a bridge.", "他们建了一座桥。"],
["consult", "/kənˈsʌlt/", "v. 咨询", "con+sult(坐)：同坐商议", "consult a doctor", "Consult an expert first.", "先咨询专家。"],
["consume", "/kənˈsjuːm/", "v. 消耗；消费", "con+sume(取)：全取", "consume energy", "Cars consume fuel.", "汽车消耗燃料。"],
["contact", "/ˈkɒntækt/", "n./v. 联系", "con+tact(触)", "keep in contact", "Stay in contact with us.", "和我们保持联系。"],
["contaminate", "/kənˈtæmɪneɪt/", "v. 污染", "con+tamin(触)+ate：弄脏", "contaminated water", "The water was contaminated.", "水被污染了。"],
["contemplate", "/ˈkɒntəmpleɪt/", "v. 沉思；考虑", "con+temple(庙)：庙中冥想", "contemplate doing", "He contemplated quitting.", "他考虑过辞职。"],
["contemporary", "/kənˈtemprəri/", "adj. 当代的；同时代的", "con+tempor(时)+ary", "contemporary art", "This is contemporary art.", "这是当代艺术。"],
["contend", "/kənˈtend/", "v. 主张；竞争", "con+tend(伸)：一同争", "contend that...", "He contends it is wrong.", "他主张这是错的。"],
["context", "/ˈkɒntekst/", "n. 背景；语境", "con+text(织)：织在一起", "in context", "Read it in context.", "结合语境读。"],
["continual", "/kənˈtɪnjuəl/", "adj. 持续的", "con+tinu(保持)+al", "continual improvement", "There is continual change.", "变化持续不断。"],
["contract", "/ˈkɒntrækt/", "n. 合同；v. 收缩", "con+tract(拉)：拉到一起", "sign a contract", "They signed a contract.", "他们签了合同。"],
["contradict", "/ˌkɒntrəˈdɪkt/", "v. 反驳；矛盾", "contra(反)+dict(说)", "contradict oneself", "His words contradict.", "他的话自相矛盾。"],
["contrary", "/ˈkɒntrəri/", "adj. 相反的", "contra(反)+ry", "on the contrary", "On the contrary, he agreed.", "相反，他同意了。"],
["contribute", "/kənˈtrɪbjuːt/", "v. 贡献", "con+tribute(给)", "contribute to", "Exercise contributes to health.", "运动有益健康。"],
["controversy", "/ˈkɒntrəvɜːsi/", "n. 争议", "contro(反)+vers(转)+y", "a political controversy", "The topic sparked controversy.", "该话题引发争议。"],
["convene", "/kənˈviːn/", "v. 召集；集会", "con+vene(来)", "convene a meeting", "They convened a summit.", "他们召开了峰会。"],
["convention", "/kənˈvenʃn/", "n. 会议；惯例", "con+vent(来)+ion", "by convention", "It is a social convention.", "这是社会惯例。"],
["convert", "/kənˈvɜːt/", "v. 转变", "con+vert(转)", "convert into", "They converted the loft.", "他们改造了阁楼。"],
["convince", "/kənˈvɪns/", "v. 使信服", "con+vince(胜)：完全胜过", "convince sb of", "He convinced the jury.", "他说服了陪审团。"],
["cooperate", "/kəʊˈɒpəreɪt/", "v. 合作", "co+oper(工作)+ate", "cooperate with", "They cooperated closely.", "他们紧密合作。"],
["cope", "/kəʊp/", "v. 应付，处理", "cope 音似‘扛破’", "cope with", "She coped with stress.", "她扛住了压力。"],
["correspond", "/ˌkɒrəˈspɒnd/", "v. 对应；通信", "cor+respond(回应)", "correspond to / with", "Profits correspond to effort.", "收益与努力对应。"],
["council", "/ˈkaʊnsl/", "n. 委员会；理事会", "coun(劝)+cil", "易混 council vs counsel", "The city council met.", "市议会开会了。"],
["counsel", "/ˈkaʊnsl/", "n./v. 建议；法律顾问", "coun(劝)+sel", "易混 counsel vs council", "Seek legal counsel.", "寻求法律建议。"],
["create", "/kriˈeɪt/", "v. 创造", "cre(长)+ate：长出来", "create value", "Art creates emotion.", "艺术创造情感。"],
["credit", "/ˈkredɪt/", "n. 信用；学分", "cred(信)+it", "on credit / course credit", "Buy it on credit.", "赊账买它。"],
["crisis", "/ˈkraɪsɪs/", "n. 危机", "cris(判)+is：决断时刻", "a financial crisis", "The crisis worsened.", "危机恶化了。"],
["crucial", "/ˈkruːʃl/", "adj. 关键的", "cruc(十字)+ial：十字路口", "crucial for/to", "Sleep is crucial for memory.", "睡眠对记忆至关重要。"],
["cumulative", "/ˈkjuːmjələtɪv/", "adj. 累积的", "cumul(堆)+ative", "cumulative effect", "The effect is cumulative.", "效果是累积的。"],
["currency", "/ˈkʌrənsi/", "n. 货币；流通", "cur(流)+ency", "a strong currency", "The currency weakened.", "货币贬值了。"],
["curriculum", "/kəˈrɪkjələm/", "n. 课程", "cur(跑)+riculum：要跑的内容", "the school curriculum", "The curriculum is broad.", "课程很广。"],
["cycle", "/ˈsaɪkl/", "n./v. 循环", "cycle 音似‘赛可’", "the water cycle", "The cycle repeats yearly.", "循环每年重复。"],
["debate", "/dɪˈbeɪt/", "n./v. 辩论", "de+bate(打)：言辞交锋", "a heated debate", "They debated the policy.", "他们辩论了政策。"],
["decade", "/ˈdekeɪd/", "n. 十年", "dec(十)+ade", "over the past decade", "The last decade saw change.", "过去十年变化巨大。"],
["decay", "/dɪˈkeɪ/", "v./n. 衰退；腐烂", "de+way(路)：走下坡", "tooth decay", "The building decayed.", "建筑腐朽了。"],
["decline", "/dɪˈklaɪn/", "v./n. 下降；拒绝", "de+cline(倾)", "on the decline", "Profits declined sharply.", "利润骤降。"],
["dedicate", "/ˈdedɪkeɪt/", "v. 致力于", "de+dic(说)+ate：宣示", "dedicate oneself to", "She dedicated her life to it.", "她毕生奉献于此。"],
["defence", "/dɪˈfens/", "n. 防御", "de+fence(打)：挡开", "in defence of", "They fought in defence.", "他们奋起防卫。"],
["define", "/dɪˈfaɪn/", "v. 定义", "de+fine(终)：定下边界", "define the term", "Define the word clearly.", "明确定义这个词。"],
["definite", "/ˈdefɪnət/", "adj. 明确的", "de+fin(终)+ite", "a definite answer", "We need a definite plan.", "我们需要明确计划。"],
["deliberate", "/dɪˈlɪbərət/", "adj. 故意的；v. 深思", "de+liber(权衡)+ate", "a deliberate act", "It was a deliberate lie.", "那是蓄意谎言。"],
["delicate", "/ˈdelɪkət/", "adj. 精致的；脆弱的", "de+lic(诱)+ate", "a delicate situation", "The matter is delicate.", "此事很微妙。"],
["demand", "/dɪˈmɑːnd/", "n./v. 要求；需求", "de+mand(命令)", "meet the demand", "Demand exceeds supply.", "供不应求。"],
["demonstrate", "/ˈdemənstreɪt/", "v. 证明；示威", "de+monstr(展示)+ate", "demonstrate that...", "The study demonstrates it.", "研究证明了这一点。"],
["denote", "/dɪˈnəʊt/", "v. 表示，意味着", "de+note(记号)", "denote A as B", "A red flag denotes danger.", "红旗表示危险。"],
["deny", "/dɪˈnaɪ/", "v. 否认", "de+ny(否)", "deny doing", "He denied the charge.", "他否认了指控。"],
["deprive", "/dɪˈpraɪv/", "v. 剥夺", "de+prive(夺)", "deprive sb of", "War deprived them of home.", "战争夺走了他们的家。"],
["derive", "/dɪˈraɪv/", "v. 源自；推导", "de+rive(河)：引出", "derive from", "Many words derive from Latin.", "许多词源自拉丁语。"],
["descend", "/dɪˈsend/", "v. 下降", "de+scend(爬)", "descend from", "They descended the hill.", "他们下了山。"],
["deserve", "/dɪˈzɜːv/", "v. 应得", "de+serve(服务)：该被服务", "deserve credit", "He deserves praise.", "他应受表扬。"],
["design", "/dɪˈzaɪn/", "v./n. 设计", "de+sign(记号)：定下标记", "design a system", "She designed the logo.", "她设计了标志。"],
["desire", "/dɪˈzaɪə/", "n./v. 渴望", "de+sire(星)：仰望所求", "a strong desire", "He has a desire to win.", "他有求胜之心。"],
["detect", "/dɪˈtekt/", "v. 探测；察觉", "de+tect(盖)：揭开", "detect a problem", "Sensors detected smoke.", "传感器探测到烟。"],
["deteriorate", "/dɪˈtɪəriəreɪt/", "v. 恶化", "de+terior(坏)+ate", "his health deteriorated", "The situation deteriorated.", "局势恶化了。"],
["deviate", "/ˈdiːvieɪt/", "v. 偏离", "de+vi(路)+ate：离路", "deviate from", "Do not deviate from the plan.", "别偏离计划。"],
["diminish", "/dɪˈmɪnɪʃ/", "v. 减少；贬低", "di+min(小)+ish", "diminish in value", "His influence diminished.", "他的影响力下降。"],
["discipline", "/ˈdɪsəplɪn/", "n. 纪律；v. 训练", "discip(学)+line", "self-discipline", "Discipline leads to success.", "自律通向成功。"],
["disclose", "/dɪsˈkləʊz/", "v. 披露", "dis+close(关)：打开", "disclose the truth", "They disclosed the data.", "他们披露了数据。"],
["disperse", "/dɪˈspɜːs/", "v. 分散；驱散", "dis+perse(撒)", "disperse the crowd", "Police dispersed them.", "警察驱散了人群。"],
["distinct", "/dɪˈstɪŋkt/", "adj. 明显的；不同的", "di+stinct(刺)：扎眼", "distinct from", "The ideas are distinct.", "这些想法明显不同。"],
["distribute", "/dɪˈstrɪbjuːt/", "v. 分发", "dis+tribute(给)", "distribute among", "They distributed aid.", "他们分发了援助。"],
["diverse", "/daɪˈvɜːs/", "adj. 多样的", "di+verse(转)：转向各方", "culturally diverse", "The city is diverse.", "这座城市多元。"],
["document", "/ˈdɒkjument/", "n. 文件；v. 记录", "docu(教)+ment", "a legal document", "Keep the document safe.", "保管好文件。"],
["domain", "/dəˈmeɪn/", "n. 领域；域名", "dom(家)+ain", "in the domain of", "This is outside my domain.", "这超出我的领域。"],
["domestic", "/dəˈmestɪk/", "adj. 国内的；家庭的", "dom(家)+estic", "domestic market", "Domestic sales grew.", "国内销售增长。"],
["dominate", "/ˈdɒmɪneɪt/", "v. 主导；支配", "domin(统治)+ate", "dominate the market", "The brand dominates.", "该品牌主导市场。"],
["draft", "/drɑːft/", "n. 草稿；v. 起草", "draft 音似‘抓夫特’", "a rough draft", "He drafted a letter.", "他起草了一封信。"],
["dramatic", "/drəˈmætɪk/", "adj. 戏剧性的；显著的", "drama+tic", "a dramatic change", "There was a dramatic rise.", "出现了显著上升。"],
["duration", "/djʊˈreɪʃn/", "n. 持续时间", "dur(持续)+ation", "for the duration", "The duration is short.", "持续时间很短。"],
["dynamic", "/daɪˈnæmɪk/", "adj. 动态的；n. 动力", "dyna(力)+mic", "a dynamic market", "The economy is dynamic.", "经济充满活力。"],
["economy", "/ɪˈkɒnəmi/", "n. 经济", "eco(家)+nomy(法)", "a weak economy", "The economy is recovering.", "经济正在复苏。"],
["Edition", "/ɪˈdɪʃn/", "n. 版本；版次", "edit(编辑)+ion", "the first edition", "This is the second edition.", "这是第二版。"],
["elaborate", "/ɪˈlæbərət/", "adj. 详尽的；v. 详述", "e+labor(劳动)+ate：精心做", "elaborate on", "Please elaborate your point.", "请详述你的观点。"],
["eliminate", "/ɪˈlɪmɪneɪt/", "v. 消除；淘汰", "e(出)+limin(门槛)+ate", "eliminate errors", "We eliminated mistakes.", "我们消除了错误。"],
["embrace", "/ɪmˈbreɪs/", "v. 拥抱；欣然接受", "em+brace(臂)：入怀", "embrace change", "They embraced the idea.", "他们欣然接受了这想法。"],
["emerge", "/ɪˈmɜːdʒ/", "v. 出现；浮现", "e(出)+merge(沉)：浮出", "emerge from", "A new leader emerged.", "一位新领袖出现了。"],
["emphasis", "/ˈemfəsɪs/", "n. 强调", "em+phas(显)+is", "place emphasis on", "We place emphasis on safety.", "我们重视安全。"],
["emphasize", "/ˈemfəsaɪz/", "v. 强调", "em+phase(阶段)+ize", "emphasize the need to", "He emphasized care.", "他强调要谨慎。"],
["empirical", "/ɪmˈpɪrɪkl/", "adj. 经验主义的", "em+pir(试)+ical：靠试", "empirical evidence", "We need empirical data.", "我们需要实证数据。"],
["enable", "/ɪˈneɪbl/", "v. 使能够", "en+able(能)", "enable sb to", "The tool enables learning.", "这工具让人能学习。"],
["encounter", "/ɪnˈkaʊntə/", "v./n. 遭遇；遇到", "en+counter(对立)", "encounter a problem", "We encountered difficulties.", "我们遇到了困难。"],
["endeavour", "/ɪnˈdevə/", "v./n. 努力；尝试", "en+deavour(应得)", "make an endeavour", "They endeavoured to help.", "他们努力帮忙。"],
["enormous", "/ɪˈnɔːməs/", "adj. 巨大的", "e(出)+norm(规则)+ous：超规", "an enormous amount", "There was enormous pressure.", "压力巨大。"],
["ensure", "/ɪnˈʃʊə/", "v. 确保", "en+sure(确实)", "ensure that...", "Ensure the door is locked.", "确保门锁好。"],
["entitle", "/ɪnˈtaɪtl/", "v. 使有权利；题名", "en+title(名)", "be entitled to", "You are entitled to a refund.", "你有权退款。"],
["environment", "/ɪnˈvaɪrənmənt/", "n. 环境", "en+viron(围)+ment", "protect the environment", "We must save the environment.", "我们必须保护环境。"],
["equip", "/ɪˈkwɪp/", "v. 装备；使具备", "equip 音似‘一奎普’", "equip with", "Schools equip students.", "学校装备学生。"],
["erase", "/ɪˈreɪz/", "v. 擦除", "e+rase(刮)", "erase the mistake", "He erased the file.", "他删除了文件。"],
["error", "/ˈerə/", "n. 错误", "err(错)+or", "a fatal error", "The report had an error.", "报告有个错误。"],
["establish", "/ɪˈstæblɪʃ/", "v. 建立；证实", "e+stable(稳)+ish", "establish a system", "They established a rule.", "他们确立了规则。"],
["estate", "/ɪˈsteɪt/", "n. 地产；财产", "e+state(站)：立下的产业", "real estate", "He invests in real estate.", "他投资房地产。"],
["estimate", "/ˈestɪmeɪt/", "v./n. 估计", "e+stim(估)+ate", "estimate the cost", "We estimated the loss.", "我们估了损失。"],
["ethnic", "/ˈeθnɪk/", "adj. 民族的", "ethn(民族)+ic", "ethnic minorities", "The region is multi-ethnic.", "该地区多民族。"],
["evaluate", "/ɪˈvæljueɪt/", "v. 评价；评估", "e+value(价值)+ate", "evaluate the effect", "We evaluated results.", "我们评估了结果。"],
["eventual", "/ɪˈventʃuəl/", "adj. 最终的", "event(事)+ual", "the eventual winner", "The eventual outcome was good.", "最终结果不错。"],
["evident", "/ˈevɪdənt/", "adj. 明显的", "e+vid(看)+ent", "self-evident", "The benefit is evident.", "好处显而易见。"],
["evolve", "/ɪˈvɒlv/", "v. 进化；演变", "e+volv(滚)：滚出", "evolve into", "Cities evolve over time.", "城市随时间演变。"],
["exceed", "/ɪkˈsiːd/", "v. 超过", "ex(出)+ceed(走)", "exceed the limit", "Costs exceeded budget.", "成本超预算了。"],
["exclude", "/ɪkˈskluːd/", "v. 排除", "ex+clude(关)", "exclude from", "Children were excluded.", "儿童被排除在外。"],
["exclusive", "/ɪkˈskluːsɪv/", "adj. 独占的；排外的", "ex+clus(关)+ive", "an exclusive club", "It is an exclusive right.", "这是独占权。"],
["execute", "/ˈeksɪkjuːt/", "v. 执行；处决", "ex+ecute(跟)：跟完", "execute a plan", "They executed the strategy.", "他们执行了战略。"],
["exert", "/ɪɡˈzɜːt/", "v. 施加；运用", "ex+sert(束)：伸出力", "exert pressure", "He exerted influence.", "他施加了影响。"],
["exhaust", "/ɪɡˈzɔːst/", "v. 耗尽；使精疲", "ex+haust(抽)：抽干", "exhaust the funds", "I am exhausted today.", "我今天累坏了。"],
["exhibit", "/ɪɡˈzɪbɪt/", "v. 展示；n. 展品", "ex+hibit(持)：拿出", "exhibit a skill", "The museum exhibits art.", "博物馆展出艺术品。"],
["expand", "/ɪkˈspænd/", "v. 扩张", "ex+pand(展开)", "expand the business", "The company expanded.", "公司扩张了。"],
["expert", "/ˈekspɜːt/", "n. 专家；adj. 专业的", "ex+pert(试)：试过", "an expert in", "He is an expert coder.", "他是编程专家。"],
["explicit", "/ɪkˈsplɪsɪt/", "adj. 明确的", "ex+plic(折)+it：摊开", "explicit instruction", "He gave explicit orders.", "他给了明确指令。"],
["exploit", "/ɪkˈsplɔɪt/", "v. 开发；剥削", "ex+ploit(用)", "exploit resources", "They exploited the oil.", "他们开发了石油。"],
["explore", "/ɪkˈsplɔː/", "v. 探索", "ex+plore(吹)：吹开", "explore the idea", "We explored the options.", "我们探讨了选项。"],
["export", "/ɪkˈspɔːt/", "v./n. 出口", "ex+port(运)", "export goods", "They export to Europe.", "他们向欧洲出口。"],
["expose", "/ɪkˈspəʊz/", "v. 暴露；使接触", "ex+pose(放)", "expose to", "Don't expose it to light.", "别让它见光。"],
["express", "/ɪkˈspres/", "v. 表达；adj. 特快的", "ex+press(压)：挤出", "express one's view", "She expressed her anger.", "她表达了愤怒。"],
["extend", "/ɪkˈstend/", "v. 延伸；延长", "ex+tend(伸)", "extend the deadline", "They extended the stay.", "他们延长了逗留。"],
["extract", "/ɪkˈstrækt/", "v. 提取；摘录", "ex+tract(拉)", "extract data", "We extracted key points.", "我们提取了要点。"],
["extraordinary", "/ɪkˈstrɔːdnri/", "adj. 非凡的", "extra(超)+ordinary", "an extraordinary talent", "She has extraordinary skill.", "她才华非凡。"],
["fabric", "/ˈfæbrɪk/", "n. 织物；结构", "fabr(做)+ic", "the social fabric", "The fabric of society.", "社会结构。"],
["facilitate", "/fəˈsɪlɪteɪt/", "v. 促进；使便利", "facil(易)+ate", "facilitate learning", "The app facilitates study.", "这应用促进学习。"],
["factor", "/ˈfæktə/", "n. 因素", "fact(做)+or", "a key factor", "Price is a factor.", "价格是个因素。"],
["feasible", "/ˈfiːzəbl/", "adj. 可行的", "feas(做)+ible", "it is feasible to", "The plan is feasible.", "计划可行。"],
["feature", "/ˈfiːtʃə/", "n. 特征；v. 以…为特色", "feat(做)+ure", "a key feature", "The phone has features.", "这手机有特色功能。"],
["federal", "/ˈfedərəl/", "adj. 联邦的", "feder(联盟)+al", "a federal system", "The country is federal.", "该国是联邦制。"],
["fee", "/fiː/", "n. 费用", "fee 音似‘费’", "a registration fee", "The fee is 50 yuan.", "费用是50元。"],
["final", "/ˈfaɪnl/", "adj. 最终的", "fin(终)+al", "the final decision", "This is the final round.", "这是最后一轮。"],
["finance", "/ˈfaɪnæns/", "n. 财政；v. 融资", "fin(终)+ance：结清", "public finance", "She works in finance.", "她做金融。"],
["finite", "/ˈfaɪnaɪt/", "adj. 有限的", "fin(终)+ite：有终点", "a finite resource", "Oil is finite.", "石油是有限的。"],
["flexible", "/ˈfleksəbl/", "adj. 灵活的", "flex(弯)+ible", "a flexible schedule", "We offer flexible hours.", "我们提供弹性工时。"],
["fluent", "/ˈfluːənt/", "adj. 流利的", "flu(流)+ent", "fluent English", "She is fluent in French.", "她法语流利。"],
["focus", "/ˈfəʊkəs/", "n./v. 焦点；集中", "focus 音似‘佛卡斯’", "focus on", "Focus on the goal.", "专注于目标。"],
["foreast", "/ˈfɔːkɑːst/", "n./v. 预测", "fore(前)+cast(掷)：向前推", "a weather forecast", "The forecast was wrong.", "预测错了。"],
["formal", "/ˈfɔːml/", "adj. 正式的", "form(形)+al", "a formal letter", "Wear formal clothes.", "穿正式服装。"],
["format", "/ˈfɔːmæt/", "n. 格式；v. 格式化", "form(形)+at", "in a new format", "Change the file format.", "改一下文件格式。"],
["formula", "/ˈfɔːmjələ/", "n. 公式；配方", "form(形)+ula", "a simple formula", "Use this formula.", "用这个公式。"],
["forthcoming", "/ˌfɔːθˈkʌmɪŋ/", "adj. 即将到来的", "forth(向前)+coming", "the forthcoming event", "The summit is forthcoming.", "峰会即将召开。"],
["foundation", "/faʊnˈdeɪʃn/", "n. 基础；基金会", "found(基)+ation", "the foundation of", "Trust is the foundation.", "信任是基础。"],
["framework", "/ˈfreɪmwɜːk/", "n. 框架", "frame(框)+work", "a legal framework", "Build a clear framework.", "建立清晰框架。"],
["function", "/ˈfʌŋkʃn/", "n. 功能；v. 运转", "funct(做)+ion", "a core function", "The device functions well.", "设备运转良好。"],
["fundamental", "/ˌfʌndəˈmentl/", "adj. 基本的", "fund(基)+mental", "a fundamental right", "Trust is fundamental.", "信任是根本。"],
["furthermore", "/ˌfɜːðəˈmɔː/", "adv. 此外", "further+more", "Furthermore, it is cheap.", "此外，它很便宜。"],
["gender", "/ˈdʒendə/", "n. 性别", "gender 音似‘性别’", "gender equality", "They promote gender equality.", "他们促进性别平等。"],
["generate", "/ˈdʒenəreɪt/", "v. 产生；生成", "gener(生)+ate", "generate income", "Solar panels generate power.", "太阳能板发电。"],
["generous", "/ˈdʒenərəs/", "adj. 慷慨的", "gener(生)+ous：肯给", "a generous gift", "He is very generous.", "他很大方。"],
["genuine", "/ˈdʒenjuɪn/", "adj. 真正的", "genu(生)+ine：原生", "genuine interest", "She showed genuine care.", "她表现出真心关怀。"],
["global", "/ˈɡləʊbl/", "adj. 全球的", "glob(球)+al", "a global issue", "Climate is a global issue.", "气候是全球性问题。"],
["goal", "/ɡəʊl/", "n. 目标", "goal 音似‘够欧’", "achieve a goal", "Set a clear goal.", "设定清晰目标。"],
["grade", "/ɡreɪd/", "n. 等级；v. 评分", "grad(级)+e", "a high grade", "The grade reflects effort.", "成绩反映努力。"],
["gradual", "/ˈɡrædʒuəl/", "adj. 逐渐的", "grad(级)+ual", "a gradual change", "There was gradual progress.", "进展是渐进的。"],
["grand", "/ɡrænd/", "adj. 宏伟的", "grand 音似‘冠的’", "a grand plan", "They held a grand ceremony.", "他们举行了盛大仪式。"],
["grant", "/ɡrɑːnt/", "v. 授予；n. 拨款", "grant 音似‘贯特’", "grant a wish", "The fund granted money.", "基金拨了款。"],
["gravity", "/ˈɡrævəti/", "n. 重力；严重性", "grav(重)+ity", "the law of gravity", "He didn't grasp the gravity.", "他没意识到严重性。"],
["guarantee", "/ˌɡærənˈtiː/", "n./v. 保证", "guar(守)+antee", "a money-back guarantee", "We guarantee quality.", "我们保证质量。"],
["guidance", "/ˈɡaɪdns/", "n. 指导", "guid(导)+ance", "under sb's guidance", "He gave me guidance.", "他给了我指导。"],
["hierarchy", "/ˈhaɪərɑːki/", "n. 等级制度", "hier(圣)+archy(统治)", "a social hierarchy", "There is a clear hierarchy.", "等级结构分明。"],
["highlight", "/ˈhaɪlaɪt/", "v. 突出；n. 亮点", "high+light(光)", "highlight the risk", "The report highlights it.", "报告突出了这点。"],
["hypothesis", "/haɪˈpɒθəsɪs/", "n. 假设", "hypo(下)+thesis(论点)", "test a hypothesis", "The hypothesis was proved.", "假设被证实了。"],
["identify", "/aɪˈdentɪfaɪ/", "v. 识别；确认", "ident(同)+ify", "identify the cause", "We identified the problem.", "我们找出了问题。"],
["ideology", "/ˌaɪdiˈɒlədʒi/", "n. 意识形态", "ideo(观念)+logy", "a political ideology", "Their ideologies differ.", "他们意识形态不同。"],
["ignorant", "/ˈɪɡnərənt/", "adj. 无知的", "i(不)+gnor(知)+ant", "be ignorant of", "He was ignorant of the law.", "他对法律无知。"],
["illustrate", "/ˈɪləstreɪt/", "v. 说明；插图", "il+lustr(光)+ate", "illustrate with a case", "Let me illustrate it.", "我举例说明。"],
["immediate", "/ɪˈmiːdiət/", "adj. 立即的", "im(无)+medi(中)+ate：无间隔", "an immediate response", "We need immediate action.", "我们需要立即行动。"],
["impact", "/ˈɪmpækt/", "n./v. 影响；冲击", "im+pact(压)", "have an impact on", "The policy had impact.", "政策产生了影响。"],
["implement", "/ˈɪmplɪment/", "v. 实施", "im+ple(满)+ment：填满执行", "implement a plan", "They implemented reforms.", "他们实施了改革。"],
["implicate", "/ˈɪmplɪkeɪt/", "v. 牵连；暗示", "im+plic(折)+ate", "be implicated in", "He was implicated in it.", "他牵扯其中。"],
["implicit", "/ɪmˈplɪsɪt/", "adj. 含蓄的；隐含的", "im+plic(折)+it：折在里面", "implicit trust", "There was implicit trust.", "存在一种默契的信任。"],
["imply", "/ɪmˈplaɪ/", "v. 暗示", "im+ply(折)：折进去", "易混 imply vs infer", "Her tone implied doubt.", "她的语气暗示怀疑。"],
["incentive", "/ɪnˈsentɪv/", "n. 激励", "in+cent(唱)+ive：刺激", "financial incentive", "Tax cuts are an incentive.", "减税是一种激励。"],
["incidence", "/ˈɪnsɪdəns/", "n. 发生率", "in+cid(落)+ence", "a high incidence", "The incidence is rising.", "发生率在上升。"],
["incline", "/ɪnˈklaɪn/", "v. 倾向于；倾斜", "in+cline(倾)", "be inclined to", "I am inclined to agree.", "我倾向于同意。"],
["incorporate", "/ɪnˈkɔːpəreɪt/", "v. 纳入；合并", "in+corpor(体)+ate", "incorporate into", "We incorporated feedback.", "我们采纳了反馈。"],
["index", "/ˈɪndeks/", "n. 指数；索引", "in+dex(示)", "a price index", "The index rose slightly.", "指数小幅上升。"],
["indicate", "/ˈɪndɪkeɪt/", "v. 表明；指示", "in+dic(说)+ate", "indicate that...", "Data indicates a trend.", "数据表明趋势。"],
["indifferent", "/ɪnˈdɪfrənt/", "adj. 漠不关心的", "in+differ(不同)+ent：无差别", "be indifferent to", "He was indifferent to it.", "他对此漠不关心。"],
["indigenous", "/ɪnˈdɪdʒənəs/", "adj. 本土的", "indi(内)+gen(生)+ous", "indigenous people", "They protect indigenous culture.", "他们保护本土文化。"],
["inevitable", "/ɪˈnevɪtəbl/", "adj. 不可避免的", "in(不)+evit(避)+able", "change is inevitable", "Change is inevitable.", "变化不可避免。"],
["infer", "/ɪnˈfɜː/", "v. 推断", "in+fer(带)：带出结论", "易混 infer vs imply", "We inferred his meaning.", "我们推断了他的意思。"],
["inherent", "/ɪnˈhɪərənt/", "adj. 固有的", "in+her(黏)+ent", "inherent risk", "Every plan has risk.", "每个计划都有固有风险。"],
["initial", "/ɪˈnɪʃl/", "adj. 最初的", "in+it(走)+ial：刚走", "the initial stage", "The initial response was good.", "初步反应不错。"],
["initiate", "/ɪˈnɪʃieɪt/", "v. 发起；开始", "in+it(走)+iate", "initiate a reform", "They initiated talks.", "他们启动了谈判。"],
["injure", "/ˈɪndʒə/", "v. 伤害", "in+jure(法)：伤到", "be injured in", "He was injured at work.", "他工伤了。"],
["innovate", "/ˈɪnəveɪt/", "v. 创新", "in+nov(新)+ate", "innovate in", "Firms must innovate.", "企业必须创新。"],
["input", "/ˈɪnpʊt/", "n./v. 输入", "in+put(放)", "user input", "Your input matters.", "你的输入很重要。"],
["insight", "/ˈɪnsaɪt/", "n. 洞察力", "in+sight(看)", "gain insight into", "She has great insight.", "她很有洞察力。"],
["insist", "/ɪnˈsɪst/", "v. 坚持要求", "in+sist(站)：站定", "insist on", "He insisted on paying.", "他坚持付钱。"],
["inspire", "/ɪnˈspaɪə/", "v. 激励；启发", "in+spire(气)：吹入气息", "inspire sb to", "The book inspired me.", "这本书启发了我。"],
["install", "/ɪnˈstɔːl/", "v. 安装；任命", "in+stall(站)：就位", "install software", "Install the app first.", "先安装应用。"],
["instant", "/ˈɪnstənt/", "adj. 立即的；n. 瞬间", "in+stant(站)：立到", "an instant reply", "We need an instant fix.", "我们需要立刻解决。"],
["instinct", "/ˈɪnstɪŋkt/", "n. 本能", "in+stinct(刺)：内生的刺", "by instinct", "Birds fly by instinct.", "鸟凭本能飞翔。"],
["institute", "/ˈɪnstɪtjuːt/", "n. 机构；v. 制定", "in+stitute(站)", "a research institute", "The institute published it.", "该机构发表了它。"],
["instruct", "/ɪnˈstrʌkt/", "v. 指示；教导", "in+struct(建)", "instruct sb to", "He instructed them to wait.", "他指示他们等候。"],
["integral", "/ˈɪntɪɡrəl/", "adj. 不可或缺的", "integr(整)+al", "an integral part", "Trust is integral to teams.", "信任对团队不可或缺。"],
["integrate", "/ˈɪntɪɡreɪt/", "v. 整合；使融入", "integr(整)+ate", "integrate into", "Immigrants integrate slowly.", "移民缓慢融入。"],
["integrity", "/ɪnˈteɡrəti/", "n. 正直；完整", "integr(整)+ity", "a man of integrity", "He is known for integrity.", "他以正直著称。"],
["intellectual", "/ˌɪntəˈlektʃuəl/", "adj. 智力的；n. 知识分子", "intel(间)+lect(选)+ual", "intellectual property", "IP means intellectual property.", "IP 即知识产权。"],
["intense", "/ɪnˈtens/", "adj. 强烈的", "in+tens(拉)+e：拉满", "intense pressure", "There was intense debate.", "辩论很激烈。"],
["interact", "/ˌɪntərˈækt/", "v. 互动", "inter(间)+act", "interact with", "Users interact with it.", "用户与之互动。"],
["interfere", "/ˌɪntəˈfɪə/", "v. 干涉；干扰", "inter(间)+fere(打)", "interfere with", "Don't interfere in this.", "别干涉此事。"],
["intermittent", "/ˌɪntəˈmɪtənt/", "adj. 间歇的", "inter(间)+mitt(放)+ent", "intermittent rain", "There was intermittent rain.", "雨时下时停。"],
["interpret", "/ɪnˈtɜːprɪt/", "v. 解读；口译", "inter+pret(说)", "interpret the data", "How do you interpret it?", "你如何解读？"],
["interval", "/ˈɪntəvl/", "n. 间隔", "inter(间)+val(墙)", "at intervals", "Rest at regular intervals.", "定时休息。"],
["intervene", "/ˌɪntəˈviːn/", "v. 干预", "inter(间)+vene(来)", "intervene in", "The UN intervened.", "联合国干预了。"],
["intimate", "/ˈɪntɪmət/", "adj. 亲密的；暗示的", "intim(内)+ate", "an intimate friend", "They are intimate friends.", "他们是密友。"],
["invoke", "/ɪnˈvəʊk/", "v. 援引；唤起", "in+vok(呼)+e", "invoke a law", "They invoked an old law.", "他们援引了旧法。"],
["invest", "/ɪnˈvest/", "v. 投资", "in+vest(衣)：穿官服→授权", "invest in", "Invest in education.", "投资教育。"],
["investigate", "/ɪnˈvestɪɡeɪt/", "v. 调查", "in+vestig(踪)+ate", "investigate the case", "Police investigated it.", "警方调查了此事。"],
["involve", "/ɪnˈvɒlv/", "v. 涉及；使参与", "in+volv(滚)", "involve sb in", "The job involves travel.", "这工作要出差。"],
["isolate", "/ˈaɪsəleɪt/", "v. 孤立", "isol(岛)+ate", "isolate from", "They isolated the patient.", "他们隔离了病人。"],
["issue", "/ˈɪʃuː/", "n. 问题；v. 发行", "issue 音似‘议题’", "a key issue", "We issued a statement.", "我们发表了声明。"],
["item", "/ˈaɪtəm/", "n. 项目；条款", "item 音似‘爱特木’", "the first item", "This is item number one.", "这是第一条。"],
["job", "/dʒɒb/", "n. 工作", "job 音似‘ job’", "a full-time job", "He lost his job.", "他失业了。"],
["joint", "/dʒɔɪnt/", "adj. 联合的；n. 关节", "join(连)+t", "a joint effort", "It was a joint project.", "这是联合项目。"],
["journal", "/ˈdʒɜːnl/", "n. 期刊；日记", "journ(日)+al", "a medical journal", "She published in a journal.", "她在期刊上发表了文章。"],
["justice", "/ˈdʒʌstɪs/", "n. 正义；司法", "just(正)+ice", "social justice", "They fought for justice.", "他们为正义而战。"],
["justify", "/ˈdʒʌstɪfaɪ/", "v. 证明…正当", "just(正)+ify", "justify the cost", "He justified the expense.", "他证明了开支合理。"],
["label", "/ˈleɪbl/", "n. 标签；v. 贴标签", "label 音似‘累包’", "put a label on", "The label shows the price.", "标签显示了价格。"],
["labor", "/ˈleɪbə/", "n. 劳动；v. 苦干", "labor 音似‘累伯’", "cheap labor", "Labor costs are rising.", "人工成本在涨。"],
["lack", "/læk/", "n./v. 缺乏", "lack 音似‘拉客’", "a lack of", "There is a lack of trust.", "缺乏信任。"],
["lag", "/læɡ/", "v./n. 落后", "lag 音似‘拉格’", "lag behind", "The economy lagged.", "经济落后了。"],
["landscape", "/ˈlændskeɪp/", "n. 风景；局势", "land+scape(景)", "the political landscape", "The landscape changed.", "局势变了。"],
["largely", "/ˈlɑːdʒli/", "adv. 主要地", "large+ly", "It is largely true.", "这大体上是真的。"],
["launch", "/lɔːntʃ/", "v./n. 发起；发射", "launch 音似‘落地启’", "launch a product", "They launched the app.", "他们发布了应用。"],
["layer", "/ˈleɪə/", "n. 层", "lay(铺)+er", "a thin layer", "Add a layer of soil.", "加一层土。"],
["lecture", "/ˈlektʃə/", "n./v. 讲座；训诫", "lect(读)+ure", "attend a lecture", "I missed the lecture.", "我错过了讲座。"],
["legacy", "/ˈleɡəsi/", "n. 遗产；遗留", "leg(法)+acy", "a cultural legacy", "They left a rich legacy.", "他们留下了丰厚遗产。"],
["legal", "/ˈliːɡl/", "adj. 法律的", "leg(法)+al", "legal advice", "Seek legal help.", "寻求法律帮助。"],
["legitimate", "/lɪˈdʒɪtɪmət/", "adj. 合法的；合理的", "leg(法)+itimate", "a legitimate concern", "That is a legitimate worry.", "那是合理的担忧。"],
["levy", "/ˈlevi/", "v. 征收；n. 税款", "levy 音似‘累维’", "levy a tax", "The state levies tax.", "国家征税。"],
["liable", "/ˈlaɪəbl/", "adj. 有责任的；易…的", "li(绑)+able", "be liable for", "You are liable for damages.", "你对损失负责。"],
["liberal", "/ˈlɪbərəl/", "adj. 自由的；开明的", "liber(自由)+al", "a liberal attitude", "He has liberal views.", "他观点开明。"],
["license", "/ˈlaɪsns/", "n. 执照；v. 许可", "lic(准)+ense", "a driving license", "Renew your license.", "续你的执照。"],
["likewise", "/ˈlaɪkwaɪz/", "adv. 同样地", "like+wise", "Likewise, he agreed.", "同样地，他同意了。"],
["link", "/lɪŋk/", "n./v. 联系", "link 音似‘领扣’", "a strong link", "There is a link between them.", "两者有联系。"],
["locate", "/ləʊˈkeɪt/", "v. 位于；查找", "loc(地方)+ate", "be located in", "The office is located downtown.", "办公室位于市中心。"],
["logic", "/ˈlɒdʒɪk/", "n. 逻辑", "log(说)+ic", "faulty logic", "His logic is sound.", "他逻辑严密。"],
["loose", "/luːs/", "adj. 松散的", "loose 音似‘路丝’", "a loose tie", "The screw is loose.", "螺丝松了。"],
["maintain", "/meɪnˈteɪn/", "v. 维持；保养", "main(手)+tain(握)", "maintain contact", "We must maintain order.", "我们必须维持秩序。"],
["major", "/ˈmeɪdʒə/", "adj. 主要的；n. 专业", "major 音似‘眉角’", "a major issue", "This is a major problem.", "这是个主要问题。"],
["manifest", "/ˈmænɪfest/", "adj. 明显的；v. 显示", "mani(手)+fest(击)：打在手上让人见", "manifest itself", "The trend manifested clearly.", "趋势清晰显现。"],
["manipulate", "/məˈnɪpjuleɪt/", "v. 操纵；篡改", "mani(手)+pulate", "manipulate data", "He manipulated the figures.", "他篡改了数据。"],
["manual", "/ˈmænjuəl/", "adj. 手动的；n. 手册", "manu(手)+al", "a manual task", "Read the user manual.", "读用户手册。"],
["margin", "/ˈmɑːdʒɪn/", "n. 边缘；利润", "margin 音似‘马金’", "on the margin", "The profit margin is thin.", "利润微薄。"],
["mass", "/mæs/", "n. 群众；adj. 大量的", "mass 音似‘马斯’", "the masses", "Mass production began.", "批量生产开始了。"],
["means", "/miːnz/", "n. 手段；财富", "mean(手段)+s", "by all means", "Education is a means to it.", "教育是一种手段。"],
["mechanism", "/ˈmekənɪzəm/", "n. 机制", "mechan(机械)+ism", "a defence mechanism", "The mechanism is unclear.", "机制尚不清楚。"],
["media", "/ˈmiːdiə/", "n. 媒体", "medi(中)+a", "social media", "The media reported it.", "媒体报道了此事。"],
["mediate", "/ˈmiːdieɪt/", "v. 调解", "medi(中)+ate", "mediate between", "They mediated the dispute.", "他们调解了争端。"],
["medical", "/ˈmedɪkl/", "adj. 医学的", "medic(医)+al", "medical care", "He needs medical help.", "他需要医疗帮助。"],
["medium", "/ˈmiːdiəm/", "n. 媒介；adj. 中等的", "medi(中)+um", "through the medium of", "It is a medium size.", "这是中号。"],
["mere", "/mɪə/", "adj. 仅仅的", "mere 音似‘弥尔’", "a mere child", "It is a mere excuse.", "那只是借口。"],
["migrate", "/maɪˈɡreɪt/", "v. 迁移", "migr(移)+ate", "migrate to cities", "Birds migrate south.", "鸟南迁。"],
["military", "/ˈmɪlətri/", "adj. 军事的", "milit(兵)+ary", "military service", "He has military experience.", "他有军旅经历。"],
["minimal", "/ˈmɪnɪml/", "adj. 最小的", "mini(小)+mal", "minimal risk", "The change is minimal.", "变化极小。"],
["minimize", "/ˈmɪnɪmaɪz/", "v. 最小化", "mini(小)+ize", "minimize risk", "We minimized the loss.", "我们把损失降到最低。"],
["minimum", "/ˈmɪnɪməm/", "n./adj. 最小(的)", "mini(小)+mum", "a minimum wage", "Set a minimum price.", "设个最低价。"],
["ministry", "/ˈmɪnɪstri/", "n. (政府)部", "mini(小)+stry", "the health ministry", "The ministry issued rules.", "该部发布了规定。"],
["minor", "/ˈmaɪnə/", "adj. 较小的；n. 未成年人", "min(小)+or", "a minor issue", "It is a minor problem.", "这是小问题。"],
["mobile", "/ˈməʊbaɪl/", "adj. 移动的", "mob(动)+ile", "a mobile phone", "Mobile payment is common.", "移动支付很普遍。"],
["mode", "/məʊd/", "n. 模式；方式", "mode 音似‘模德’", "a new mode", "Switch to night mode.", "切到夜间模式。"],
["modify", "/ˈmɒdɪfaɪ/", "v. 修改", "mod(量)+ify：调量", "modify the plan", "We modified the design.", "我们修改了设计。"],
["monitor", "/ˈmɒnɪtə/", "v. 监控；n. 显示器", "monit(警)+or", "monitor progress", "They monitored the rate.", "他们监控了比率。"],
["motive", "/ˈməʊtɪv/", "n. 动机", "mot(动)+ive", "a hidden motive", "What was his motive?", "他的动机是什么？"],
["mutual", "/ˈmjuːtʃuəl/", "adj. 相互的", "mutu(交换)+al", "mutual benefit", "We have mutual respect.", "我们相互尊重。"],
["narrative", "/ˈnærətɪv/", "n. 叙述；adj. 叙事的", "narr(讲)+ative", "a coherent narrative", "The narrative is clear.", "叙述清晰。"],
["narrow", "/ˈnærəʊ/", "adj. 狭窄的；v. 缩小", "narrow 音似‘窄罗’", "a narrow road", "Narrow the focus.", "缩小焦点。"],
["nation", "/ˈneɪʃn/", "n. 国家；民族", "nat(生)+ion", "a developing nation", "The nation is growing.", "国家在发展。"],
["native", "/ˈneɪtɪv/", "adj. 本地的；n. 本地人", "nat(生)+ive", "native speakers", "She is a native speaker.", "她是母语者。"],
["natural", "/ˈnætʃrəl/", "adj. 自然的", "nat(生)+ural", "natural resources", "We waste natural gas.", "我们浪费天然气。"],
["neglect", "/nɪˈɡlekt/", "v. 忽视", "neg(不)+lect(选)", "neglect one's duty", "He neglected his health.", "他忽视了健康。"],
["negotiate", "/nɪˈɡəʊʃieɪt/", "v. 谈判", "neg(无)+oti(轻松)+ate：认真谈", "negotiate a deal", "They negotiated a contract.", "他们谈成了一笔合同。"],
["neutral", "/ˈnjuːtrəl/", "adj. 中立的；中性的", "neutr(中)+al", "a neutral stance", "The country stayed neutral.", "该国保持中立。"],
["nevertheless", "/ˌnevəðəˈles/", "adv. 然而", "never+the+less", "Nevertheless, he tried.", "然而，他试了。"],
["notion", "/ˈnəʊʃn/", "n. 概念；念头", "not(知)+ion", "the notion that...", "The notion is outdated.", "这观念过时了。"],
["notwithstanding", "/ˌnɒtwɪθˈstændɪŋ/", "prep./adv. 尽管", "not+with+standing", "Notwithstanding the rain, we went.", "尽管下雨我们还是去了。"],
["nuclear", "/ˈnjuːkliə/", "adj. 核能的；核心的", "nucle(核)+ar", "nuclear energy", "They debated nuclear power.", "他们辩论了核能。"],
["objective", "/əbˈdʒektɪv/", "adj. 客观的；n. 目标", "object(对象)+ive", "stay objective", "Journalists should be objective.", "记者应客观。"],
["obligation", "/ˌɒblɪˈɡeɪʃn/", "n. 义务", "ob+lig(绑)+ation", "a legal obligation", "We have an obligation.", "我们有义务。"],
["observe", "/əbˈzɜːv/", "v. 观察；遵守", "ob+serve(守)", "observe the rule", "He observed the stars.", "他观测了星空。"],
["obtain", "/əbˈteɪn/", "v. 获得", "ob+tain(拿)", "obtain a degree", "She obtained a licence.", "她拿到了执照。"],
["obvious", "/ˈɒbviəs/", "adj. 明显的", "ob+vi(路)+ous：挡路", "it is obvious that", "The answer is obvious.", "答案很明显。"],
["occupy", "/ˈɒkjupaɪ/", "v. 占据；使忙碌", "oc+cupy(抓)", "occupy one's mind", "The task occupied him.", "任务占满了他的心思。"],
["occur", "/əˈkɜː/", "v. 发生；想到", "oc+cur(跑)：跑来", "occur to sb", "An idea occurred to me.", "我想到一个主意。"],
["odd", "/ɒd/", "adj. 奇怪的；奇数的", "odd 音似‘奥德’", "an odd number", "That is rather odd.", "那有点怪。"],
["offence", "/əˈfens/", "n. 冒犯；罪行", "of+fence(打)", "an offence against", "It is an offence to cheat.", "作弊是犯罪。"],
["offset", "/ˈɒfset/", "v. 抵消", "off+set(放)", "offset the cost", "The gain offset the loss.", "收益抵消了损失。"],
["ongoing", "/ˈɒnɡəʊɪŋ/", "adj. 持续的", "on+going", "an ongoing project", "The debate is ongoing.", "辩论仍在继续。"],
["online", "/ˌɒnˈlaɪn/", "adj./adv. 在线的", "on+line", "an online course", "Take an online class.", "上一门线上课。"],
["onset", "/ˈɒnset/", "n. 开始；发作", "on+set(落)", "the onset of", "the onset of winter", "冬天伊始。"],
["opacity", "/əʊˈpæsəti/", "n. 不透明；含糊", "opac(暗)+ity", "political opacity", "The opacity of the rule.", "规则含糊。"],
["operate", "/ˈɒpəreɪt/", "v. 运转；操作", "oper(工作)+ate", "operate a machine", "The hospital operates well.", "医院运转良好。"],
["opinion", "/əˈpɪnjən/", "n. 意见", "opin(认为)+ion", "in my opinion", "It is a matter of opinion.", "这是见仁见智。"],
["opponent", "/əˈpəʊnənt/", "n. 对手", "op+pon(放)+ent：放在对面", "a worthy opponent", "He beat his opponent.", "他击败了对手。"],
["opportunity", "/ˌɒpəˈtjuːnəti/", "n. 机会", "op+port(港)+unity：好风靠港", "a golden opportunity", "Seize the opportunity.", "抓住机会。"],
["oppose", "/əˈpəʊz/", "v. 反对", "op+pose(放)：放在对面", "oppose a plan", "They opposed the law.", "他们反对该法。"],
["optical", "/ˈɒptɪkl/", "adj. 光学的", "opt(看)+ical", "optical fibre", "Optical fibre is fast.", "光纤很快。"],
["optimistic", "/ˌɒptɪˈmɪstɪk/", "adj. 乐观的", "optim(最佳)+istic", "an optimistic view", "She is optimistic about it.", "她对此乐观。"],
["option", "/ˈɒpʃn/", "n. 选择", "opt(选)+ion", "keep your options open", "We have several options.", "我们有几个选项。"],
["orbit", "/ˈɔːbɪt/", "n. 轨道；v. 绕行", "orbit 音似‘奥比特’", "in orbit", "The satellite is in orbit.", "卫星在轨运行。"],
["order", "/ˈɔːdə/", "n./v. 秩序；命令", "order 音似‘奥德’", "in order", "Put it in order.", "把它整理好。"],
["organ", "/ˈɔːɡən/", "n. 器官；机构", "organ 音似‘奥根’", "a government organ", "The organ published it.", "该机构发表了它。"],
["organism", "/ˈɔːɡənɪzəm/", "n. 生物；有机体", "organ+ism", "a living organism", "A cell is an organism.", "细胞是有机体。"],
["organize", "/ˈɔːɡənaɪz/", "v. 组织", "organ+ize", "organize an event", "They organized a rally.", "他们组织了集会。"],
["outcome", "/ˈaʊtkʌm/", "n. 结果", "out+come(来)", "the final outcome", "The outcome was positive.", "结果积极。"],
["outlet", "/ˈaʊtlet/", "n. 出口；销路", "out+let(放)", "a retail outlet", "Find an outlet for stress.", "给压力找个出口。"],
["outline", "/ˈaʊtlaɪn/", "n. 大纲；v. 概述", "out+line(线)", "an outline of", "Give an outline first.", "先给个大纲。"],
["output", "/ˈaʊtpʊt/", "n. 产出", "out+put(放)", "industrial output", "Output has increased.", "产出增加了。"],
["overall", "/ˌəʊvərˈɔːl/", "adj. 总体的", "over+all", "the overall trend", "The overall picture is good.", "总体向好。"],
["overcome", "/ˌəʊvəˈkʌm/", "v. 克服", "over+come(来)", "overcome difficulties", "We overcame the crisis.", "我们克服了危机。"],
["overlap", "/ˌəʊvəˈlæp/", "v./n. 重叠", "over+lap(折)", "overlap with", "The tasks overlap.", "任务有重叠。"],
["overseas", "/ˌəʊvəˈsiːz/", "adj./adv. 海外的", "over+seas", "overseas markets", "They expanded overseas.", "他们向海外扩张。"],
["oversee", "/ˌəʊvəˈsiː/", "v. 监督", "over+see(看)", "oversee the project", "He oversaw the build.", "他监督了建设。"],
["overturn", "/ˌəʊvəˈtɜːn/", "v. 推翻；倾覆", "over+turn(转)", "overturn a verdict", "The court overturned it.", "法院推翻了判决。"],
["overwhelm", "/ˌəʊvəˈwelm/", "v. 淹没；压倒", "over+whelm(浪)", "be overwhelmed by", "She was overwhelmed by work.", "她被工作压垮。"],
["pace", "/peɪs/", "n. 步伐；v. 踱步", "pace 音似‘佩斯’", "keep pace with", "We kept pace with demand.", "我们跟上了需求。"],
["panel", "/ˈpænl/", "n. 专家小组；面板", "panel 音似‘盘尔’", "a review panel", "The panel met today.", "小组今天开会了。"],
["paradigm", "/ˈpærədaɪm/", "n. 范式", "para(旁)+digm(示)", "a new paradigm", "This is a paradigm shift.", "这是范式转变。"],
["parallel", "/ˈpærəlel/", "adj. 平行的；n. 相似处", "para(旁)+llel(彼此)", "in parallel with", "There is a parallel case.", "有个类似案例。"],
["parity", "/ˈpærəti/", "n. 平等；等价", "par(等)+ity", "achieve parity", "They sought wage parity.", "他们争取同工同酬。"],
["participate", "/pɑːˈtɪsɪpeɪt/", "v. 参与", "parti(部分)+cip(取)+ate", "participate in", "She participated actively.", "她积极参与。"],
["particular", "/pəˈtɪkjələ/", "adj. 特别的；n. 细节", "part(部分)+icular", "in particular", "He loves music in particular.", "他尤其爱音乐。"],
["passive", "/ˈpæsɪv/", "adj. 被动的", "pass(受)+ive", "a passive role", "He took a passive stance.", "他采取被动姿态。"],
["pastime", "/ˈpɑːstaɪm/", "n. 消遣", "pas(过)+time", "a popular pastime", "Reading is my pastime.", "阅读是我的消遣。"],
["patch", "/pætʃ/", "n. 补丁；v. 修补", "patch 音似‘帕奇’", "a software patch", "They patched the bug.", "他们修补了漏洞。"],
["patent", "/ˈpeɪtnt/", "n. 专利；adj. 明显的", "pat(开)+ent：公开", "file a patent", "He holds a patent.", "他持有一项专利。"],
["pathway", "/ˈpɑːθweɪ/", "n. 路径", "path+way", "a clear pathway", "We found a pathway.", "我们找到了路径。"],
["patience", "/ˈpeɪʃns/", "n. 耐心", "pati(受)+ence", "with patience", "Patience is a virtue.", "耐心是美德。"],
["pattern", "/ˈpætn/", "n. 模式；v. 仿制", "pattern 音似‘帕特恩’", "a clear pattern", "We saw a pattern.", "我们看出一种模式。"],
["peak", "/piːk/", "n. 顶峰；adj. 最高的", "peak 音似‘匹克’", "at its peak", "Sales peaked in June.", "销量在六月达峰。"],
["peer", "/pɪə/", "n. 同龄人；v. 凝视", "peer 音似‘皮尔’", "a peer group", "He was judged by peers.", "由同侪评判他。"],
["penalty", "/ˈpenəlti/", "n. 惩罚；罚金", "pen(罚)+alty", "a heavy penalty", "The penalty is severe.", "处罚很重。"],
["pending", "/ˈpendɪŋ/", "adj. 待定的", "pend(挂)+ing：挂着", "a pending case", "The case is pending.", "案件待审。"],
["perceive", "/pəˈsiːv/", "v. 感知；认为", "per(全)+ceive(拿)：全抓住", "perceive as", "She is perceived as strict.", "她被认为严厉。"],
["perfect", "/ˈpɜːfɪkt/", "adj. 完美的", "per(全)+fect(做)：做到极致", "a perfect match", "The fit is perfect.", "契合完美。"],
["perform", "/pəˈfɔːm/", "v. 执行；表演", "per+form(形)：成形", "perform a task", "They performed well.", "他们表现出色。"],
["permanent", "/ˈpɜːmənənt/", "adj. 永久的", "per(全)+man(留)+ent", "a permanent job", "He seeks permanent work.", "他找固定工作。"],
["permeate", "/ˈpɜːmieɪt/", "v. 渗透；弥漫", "per+meate(通过)", "permeate through", "The smell permeated the room.", "气味弥漫房间。"],
["permission", "/pəˈmɪʃn/", "n. 许可", "per+miss(放)+ion", "with permission", "Ask for permission first.", "先请求许可。"],
["permit", "/pəˈmɪt/", "v. 允许；n. 许可证", "per+mit(放)", "permit sb to", "Smoking is not permitted.", "禁止吸烟。"],
["persist", "/pəˈsɪst/", "v. 坚持；持续", "per+sist(站)", "persist in", "He persisted despite failure.", "他虽败仍坚持。"],
["personnel", "/ˌpɜːsəˈnel/", "n. 人员", "person+nel", "medical personnel", "The personnel were trained.", "人员受过训练。"],
["perspective", "/pəˈspektɪv/", "n. 视角", "per+spect(看)+ive", "from my perspective", "It offers a new perspective.", "它提供新视角。"],
["persuade", "/pəˈsweɪd/", "v. 说服", "per+suade(甜)：说软话", "persuade sb to", "She persuaded him to stay.", "她劝他留下。"],
["pessimistic", "/ˌpesɪˈmɪstɪk/", "adj. 悲观的", "pessim(最差)+istic", "a pessimistic view", "He is pessimistic about it.", "他对此悲观。"],
["phenomenon", "/fəˈnɒmɪnən/", "n. 现象", "pheno(显)+menon", "a natural phenomenon", "It is a rare phenomenon.", "这是罕见现象。"],
["philosophy", "/fəˈlɒsəfi/", "n. 哲学", "philo(爱)+sophy(智)", "a philosophy of life", "He has a clear philosophy.", "他有清晰的人生观。"],
["physical", "/ˈfɪzɪkl/", "adj. 身体的；物理的", "physic(自然)+al", "physical health", "Exercise improves physical health.", "运动改善身体健康。"],
["pilot", "/ˈpaɪlət/", "n. 飞行员；adj. 试点的", "pilot 音似‘派勒特’", "a pilot project", "They launched a pilot.", "他们启动了试点。"],
["plateau", "/ˈplætəʊ/", "n. 高原；v. 停滞", "plateau 音似‘普拉托’", "reach a plateau", "Growth reached a plateau.", "增长陷入停滞。"],
["platform", "/ˈplætfɔːm/", "n. 平台", "plat(平)+form", "an online platform", "The platform connects users.", "平台连接用户。"],
["plausible", "/ˈplɔːzəbl/", "adj. 看似合理的", "plaus(赞)+ible", "a plausible excuse", "His story is plausible.", "他的说法看似合理。"],
["plead", "/pliːd/", "v. 恳求；辩护", "plead 音似‘普利德’", "plead guilty", "He pleaded for mercy.", "他恳求宽恕。"],
["pledge", "/pledʒ/", "n./v. 承诺；抵押", "pledge 音似‘普莱吉’", "make a pledge", "They pledged support.", "他们承诺支持。"],
["policy", "/ˈpɒləsi/", "n. 政策", "poli(城)+cy", "a foreign policy", "The policy changed.", "政策变了。"],
["polish", "/ˈpɒlɪʃ/", "v. 磨光；n. 润色", "polish 音似‘抛光’", "polish the draft", "Polish your writing.", "润色你的文章。"],
["portion", "/ˈpɔːʃn/", "n. 部分；v. 分配", "port(分)+ion", "a large portion", "A portion goes to tax.", "一部分交了税。"],
["pose", "/pəʊz/", "v. 造成；摆姿", "pose 音似‘剖兹’", "pose a risk", "It poses a threat.", "它构成威胁。"],
["posit", "/ˈpɒzɪt/", "v. 假定；安置", "pos(放)+it", "posit that...", "He posited a theory.", "他提出了一个理论。"],
["potential", "/pəˈtenʃl/", "adj. 潜在的；n. 潜力", "poten(能)+tial", "a potential risk", "She has great potential.", "她潜力巨大。"],
["poverty", "/ˈpɒvəti/", "n. 贫困", "povert(贫)+y", "in poverty", "They fought poverty.", "他们对抗贫困。"],
["precise", "/prɪˈsaɪs/", "adj. 精确的", "pre(前)+cise(切)", "to be precise", "Give a precise figure.", "给个精确数字。"],
["predict", "/prɪˈdɪkt/", "v. 预测", "pre+dict(说)", "predict the result", "Economists predicted it.", "经济学家预测了它。"],
["predominant", "/prɪˈdɒmɪnənt/", "adj. 主导的", "pre+domin(统治)+ant", "the predominant factor", "Cost is predominant.", "成本占主导。"],
["preference", "/ˈprefrəns/", "n. 偏好", "pre+fer(带)+ence：先拿来", "a strong preference", "She has a preference.", "她有偏好。"],
["preliminary", "/prɪˈlɪmɪnəri/", "adj. 初步的", "pre+limin(门槛)+ary", "a preliminary study", "This is a preliminary step.", "这是初步步骤。"],
["prescribe", "/prɪˈskraɪb/", "v. 规定；开(处方)", "pre+scribe(写)：先写好", "prescribe a drug", "The doctor prescribed it.", "医生开了药。"],
["presence", "/ˈprezns/", "n. 存在；在场", "pre+sence(在)", "in the presence of", "His presence calmed us.", "他在场让我们安心。"],
["present", "/ˈpreznt/", "adj. 当前的；v. 呈现", "pre+sent(在)", "at present", "He presented his view.", "他陈述了观点。"],
["preserve", "/prɪˈzɜːv/", "v. 保护；保存", "pre+serve(守)", "preserve the forest", "We must preserve nature.", "我们必须保护自然。"],
["press", "/pres/", "v./n. 压；新闻界", "press 音似‘普雷斯’", "the free press", "The press reported it.", "新闻界报道了。"],
["presume", "/prɪˈzjuːm/", "v. 推测；假定", "pre+sume(拿)", "presume that...", "I presume you agree.", "我推测你同意。"],
["prevail", "/prɪˈveɪl/", "v. 盛行；获胜", "pre+vail(强)", "prevail over", "Reason prevailed.", "理性占了上风。"],
["prevalent", "/ˈprevələnt/", "adj. 普遍的", "pre+val(强)+ent", "prevalent among", "This view is prevalent.", "这观点很普遍。"],
["prevent", "/prɪˈvent/", "v. 预防；阻止", "pre+vent(来)：挡在前面", "prevent from", "We must prevent it.", "我们必须阻止它。"],
["previous", "/ˈpriːviəs/", "adj. 先前的", "pre+vi(路)+ous：前面的路", "on a previous occasion", "As mentioned previously.", "如先前所述。"],
["primary", "/ˈpraɪməri/", "adj. 主要的；初级的", "prim(首)+ary", "a primary goal", "Education is primary.", "教育是第一位的。"],
["prime", "/praɪm/", "adj. 首要的；n. 盛年", "prim(首)", "a prime example", "This is a prime case.", "这是典型例子。"],
["principal", "/ˈprɪnsəpl/", "adj. 主要的；n. 校长", "prin(首)+cip(取)+al", "易混 principal vs principle", "The principal agreed.", "校长同意了。"],
["principle", "/ˈprɪnsəpl/", "n. 原则", "prin(首)+cip+le", "易混 principle vs principal", "He stood by his principle.", "他坚守原则。"],
["priority", "/praɪˈɒrəti/", "n. 优先事项", "prior(前)+ity", "top priority", "Safety is the priority.", "安全是头等大事。"],
["prohibit", "/prəˈhɪbɪt/", "v. 禁止", "pro+hibit(持)：在前拦住", "prohibit smoking", "Smoking is prohibited.", "禁止吸烟。"],
["promote", "/prəˈməʊt/", "v. 促进；提拔", "pro+mote(动)：向前推", "promote growth", "The policy promotes growth.", "政策促进增长。"],
["prompt", "/prɒmpt/", "adj. 迅速的；v. 促使", "prompt 音似‘普绕姆普特’", "a prompt reply", "The crisis prompted action.", "危机促使了行动。"],
["pronounce", "/prəˈnaʊns/", "v. 发音；宣布", "pro+nounce(说)", "pronounce clearly", "Pronounce each word.", "把每个词读清。"],
["proof", "/pruːf/", "n. 证据；adj. 防…的", "proof 音似‘普鲁夫’", "solid proof", "We need proof.", "我们需要证据。"],
["proper", "/ˈprɒpə/", "adj. 适当的", "pro+per(通过)", "proper procedure", "Follow proper steps.", "按正确步骤来。"],
["property", "/ˈprɒpəti/", "n. 财产；性质", "pro+per(拥有)+ty", "private property", "Respect private property.", "尊重私有财产。"],
["proportion", "/prəˈpɔːʃn/", "n. 比例", "pro+port(分)+ion", "a large proportion", "A proportion stayed.", "一部分人留了下来。"],
["propose", "/prəˈpəʊz/", "v. 提议；求婚", "pro+pose(放)", "propose a plan", "He proposed a solution.", "他提出了方案。"],
["prospect", "/ˈprɒspekt/", "n. 前景；v. 勘探", "pro+spect(看)", "a bright prospect", "The prospect is good.", "前景不错。"],
["prospective", "/prəˈspektɪv/", "adj. 预期的；潜在的", "pro+spect(看)+ive", "a prospective buyer", "A prospective client came.", "一位潜在客户来了。"],
["protect", "/prəˈtekt/", "v. 保护", "pro+tect(盖)", "protect from", "Protect your eyes.", "保护你的眼睛。"],
["protocol", "/ˈprəʊtəkɒl/", "n. 协议；规程", "proto(首)+col(胶)", "follow the protocol", "Follow safety protocol.", "遵守安全规程。"],
["provide", "/prəˈvaɪd/", "v. 提供", "pro+vid(看)：向前看顾", "provide for", "They provided aid.", "他们提供了援助。"],
["provoke", "/prəˈvəʊk/", "v. 挑衅；激起", "pro+vok(呼)+e：引出", "provoke a reaction", "His words provoked anger.", "他的话激起了愤怒。"],
["publish", "/ˈpʌblɪʃ/", "v. 出版；发布", "publ(公众)+ish", "publish a book", "She published a novel.", "她出版了一本小说。"],
["pursue", "/pəˈsjuː/", "v. 追求；从事", "pur(前)+sue(跟随)", "pursue a career", "He pursued his dream.", "他追求梦想。"],
["qualify", "/ˈkwɒlɪfaɪ/", "v. 使合格；限定", "qual(质)+ify", "qualify for", "She qualified as a doctor.", "她取得了医生资格。"],
["quality", "/ˈkwɒləti/", "n. 质量；adj. 优质的", "qual(质)+ity", "high quality", "We value quality.", "我们看重质量。"],
["quantify", "/ˈkwɒntɪfaɪ/", "v. 量化", "quant(量)+ify", "quantify the impact", "We cannot quantify it.", "我们无法量化它。"],
["quarter", "/ˈkwɔːtə/", "n. 四分之一；季度", "quarter 音似‘括特’", "in the first quarter", "Sales rose this quarter.", "本季销量上升。"],
["questionnaire", "/ˌkwestʃəˈneə/", "n. 问卷", "question+naire", "fill in a questionnaire", "Complete the questionnaire.", "填好问卷。"],
["radical", "/ˈrædɪkl/", "adj. 激进的；根本的", "radic(根)+al", "a radical change", "The reform is radical.", "改革很彻底。"],
["random", "/ˈrændəm/", "adj. 随机的", "random 音似‘乱登’", "at random", "Pick one at random.", "随机抽一个。"],
["range", "/reɪndʒ/", "n. 范围；v. 变动", "range 音似‘润吉’", "a wide range", "Prices range from 10 to 50.", "价格从10到50不等。"],
["rank", "/ræŋk/", "n. 等级；v. 排名", "rank 音似‘朗克’", "a high rank", "He ranks first.", "他排第一。"],
["rapid", "/ˈræpɪd/", "adj. 迅速的", "rapid 音似‘瑞皮德’", "rapid growth", "There was rapid change.", "变化迅速。"],
["rational", "/ˈræʃnəl/", "adj. 理性的", "ratio(比)+nal", "a rational choice", "Make a rational decision.", "做理性决定。"],
["react", "/riˈækt/", "v. 反应；反抗", "re+act(动)", "react to", "How did he react?", "他有何反应？"],
["readily", "/ˈredɪli/", "adv. 容易地；乐意地", "ready+ly", "It is readily available.", "它很容易获得。"],
["realm", "/relm/", "n. 领域；王国", "realm 音似‘瑞尔姆’", "in the realm of", "This is in my realm.", "这在我领域之内。"],
["rebel", "/ˈrebl/", "n. 反叛者；v. 反叛", "re+bel(战)", "rebel against", "They rebelled against it.", "他们反抗它。"],
["recall", "/rɪˈkɔːl/", "v. 回想起；召回", "re+call(叫)", "recall an event", "I recall the day clearly.", "我清晰记得那天。"],
["receive", "/rɪˈsiːv/", "v. 收到", "re+ceive(拿)", "receive a letter", "She received good news.", "她收到了好消息。"],
["recession", "/rɪˈseʃn/", "n. 经济衰退", "re+cess(退)+ion", "a deep recession", "The recession ended.", "衰退结束了。"],
["recipe", "/ˈresəpi/", "n. 食谱；诀窍", "re+cipe(取)", "a recipe for success", "Diligence is the recipe.", "勤奋是成功诀窍。"],
["recognize", "/ˈrekəɡnaɪz/", "v. 认出；承认", "re+cogn(知)+ize", "recognize a face", "They recognized the risk.", "他们认清了风险。"],
["recommend", "/ˌrekəˈmend/", "v. 推荐", "re+commend(委托)", "recommend doing", "I recommend this book.", "我推荐这本书。"],
["recover", "/rɪˈkʌvə/", "v. 恢复；找回", "re+cover(盖)", "recover from", "He recovered quickly.", "他恢复得很快。"],
["recruit", "/rɪˈkruːt/", "v. 招募；n. 新兵", "re+cruit(长)", "recruit staff", "They recruited engineers.", "他们招募了工程师。"],
["reduce", "/rɪˈdjuːs/", "v. 减少", "re+duce(引)：往回引", "reduce costs", "We reduced waste.", "我们减少了浪费。"],
["redundant", "/rɪˈdʌndənt/", "adj. 冗余的", "re+und(波)+ant：多馀", "make sb redundant", "The post became redundant.", "该职位被裁撤。"],
["refer", "/rɪˈfɜː/", "v. 提及；参考", "re+fer(带)", "refer to", "The note refers to it.", "备注提到了它。"],
["reflect", "/rɪˈflekt/", "v. 反映；反思", "re+flect(折)", "reflect on", "The book reflects society.", "书反映了社会。"],
["reform", "/rɪˈfɔːm/", "v./n. 改革", "re+form(形)", "reform the system", "They reformed education.", "他们改革了教育。"],
["refugee", "/ˌrefjuˈdʒiː/", "n. 难民", "re+fug(逃)+ee", "war refugees", "The camp housed refugees.", "营地收容了难民。"],
["refuse", "/rɪˈfjuːz/", "v. 拒绝", "re+fuse(流)：往回挡", "refuse to do", "He refused the offer.", "他拒绝了提议。"],
["regard", "/rɪˈɡɑːd/", "v. 看待；n. 尊敬", "re+gard(看)", "with regard to", "I regard him highly.", "我很敬重他。"],
["regime", "/reɪˈʒiːm/", "n. 政权；体制", "reg(统治)+ime", "a new regime", "The regime collapsed.", "政权垮台了。"],
["region", "/ˈriːdʒən/", "n. 地区", "reg(统治)+ion", "in the region of", "The region is mountainous.", "该地区多山。"],
["register", "/ˈredʒɪstə/", "v. 登记；n. 登记簿", "re+gister(载)", "register a birth", "You must register first.", "你必须先登记。"],
["regulate", "/ˈreɡjuleɪt/", "v. 监管；调节", "reg(规)+ulate", "regulate the market", "The state regulates banks.", "国家监管银行。"],
["reinforce", "/ˌriːɪnˈfɔːs/", "v. 加强；加固", "re+in+force", "reinforce a habit", "Praise reinforces learning.", "表扬强化学习。"],
["reject", "/rɪˈdʒekt/", "v. 拒绝；驳回", "re+ject(投)：往回扔", "reject a claim", "The paper was rejected.", "论文被拒了。"],
["relate", "/rɪˈleɪt/", "v. 有关联；讲述", "re+late(带)", "relate to", "She related her story.", "她讲述了经历。"],
["release", "/rɪˈliːs/", "v./n. 释放；发布", "re+lease(松)", "release a film", "They released the report.", "他们发布了报告。"],
["relevant", "/ˈreləvənt/", "adj. 相关的", "re+lev(举)+ant：举出关系", "relevant to", "This is relevant to us.", "这与我们相关。"],
["reliable", "/rɪˈlaɪəbl/", "adj. 可靠的", "re+li(靠)+able", "a reliable source", "He is a reliable friend.", "他是可靠的朋友。"],
["relief", "/rɪˈliːf/", "n. 缓解；宽慰", "re+lief(举)：卸下", "a sense of relief", "The aid brought relief.", "援助带来了缓解。"],
["religion", "/rɪˈlɪdʒən/", "n. 宗教", "re+lig(绑)+ion", "freedom of religion", "They respect all religions.", "他们尊重所有宗教。"],
["reluctant", "/rɪˈlʌktənt/", "adj. 不情愿的", "re+luct(挣扎)+ant", "be reluctant to", "He was reluctant to go.", "他不情愿去。"],
["rely", "/rɪˈlaɪ/", "v. 依赖", "re+ly(靠)", "rely on", "We rely on data.", "我们依赖数据。"],
["remain", "/rɪˈmeɪn/", "v. 保持；剩余", "re+main(留)", "remain calm", "Much remains to be done.", "仍有许多待办。"],
["remark", "/rɪˈmɑːk/", "v./n. 评论；注意", "re+mark(标)", "remark on", "She remarked on the change.", "她评论了变化。"],
["remedy", "/ˈremədi/", "n. 补救；v. 纠正", "re+medy(治)", "a legal remedy", "There is no easy remedy.", "没有简单的补救。"],
["remember", "/rɪˈmembə/", "v. 记得", "re+member(忆)", "remember to", "I remember the song.", "我记得那首歌。"],
["remind", "/rɪˈmaɪnd/", "v. 提醒", "re+mind(心)", "remind sb of", "Remind me later.", "稍后提醒我。"],
["remote", "/rɪˈməʊt/", "adj. 遥远的；远程的", "re+mote(移)：移远", "remote areas", "He works remotely.", "他远程工作。"],
["remove", "/rɪˈmuːv/", "v. 移除", "re+move(动)", "remove a barrier", "Remove the obstacle.", "移除障碍。"],
["render", "/ˈrendə/", "v. 致使；提供", "render 音似‘伦德’", "render it useless", "The crash rendered it dead.", "崩溃让它报废了。"],
["renovate", "/ˈrenəveɪt/", "v. 翻新", "re+nov(新)+ate", "renovate a house", "They renovated the office.", "他们翻新了办公室。"],
["repair", "/rɪˈpeə/", "v./n. 修理", "re+pair(修)", "repair the damage", "We repaired the roof.", "我们修了屋顶。"],
["repeat", "/rɪˈpiːt/", "v. 重复", "re+peat(求)", "repeat after me", "Repeat the sentence.", "跟读这句。"],
["replace", "/rɪˈpleɪs/", "v. 取代；更换", "re+place(位)", "replace with", "We replaced the old system.", "我们换掉了旧系统。"],
["report", "/rɪˈpɔːt/", "v./n. 报告", "re+port(运)", "report on", "She reported the findings.", "她汇报了发现。"],
["represent", "/ˌreprɪˈzent/", "v. 代表；象征", "re+present(呈现)", "represent a group", "He represents the firm.", "他代表公司。"],
["republish", "/riːˈpʌblɪʃ/", "v. 重印；重申", "re+publish", "republish the article", "They republished the essay.", "他们重刊了文章。"],
["request", "/rɪˈkwest/", "v./n. 请求", "re+quest(求)", "request a copy", "He requested a meeting.", "他请求开会。"],
["require", "/rɪˈkwaɪə/", "v. 需要", "re+quire(求)", "require sb to", "The job requires skill.", "这工作需要技术。"],
["rescue", "/ˈreskjuː/", "v./n. 救援", "re+scue(抖)", "rescue a child", "They rescued the cat.", "他们救了猫。"],
["research", "/rɪˈsɜːtʃ/", "n./v. 研究", "re+search(查)", "do research on", "She researches climate.", "她研究气候。"],
["resemble", "/rɪˈzembl/", "v. 类似", "re+semble(同)", "resemble each other", "They resemble their father.", "他们像父亲。"],
["reserve", "/rɪˈzɜːv/", "v. 保留；n. 储备", "re+serve(守)", "reserve a seat", "We reserve the right.", "我们保留权利。"],
["reside", "/rɪˈzaɪd/", "v. 居住；存在", "re+side(坐)", "reside in", "He resides abroad.", "他旅居海外。"],
["resign", "/rɪˈzaɪn/", "v. 辞职；顺从", "re+sign(签)：交回签", "resign from", "He resigned last month.", "他上月辞职了。"],
["resist", "/rɪˈzɪst/", "v. 抵抗", "re+sist(站)", "resist temptation", "She resisted the urge.", "她抵抗了冲动。"],
["resolve", "/rɪˈzɒlv/", "v. 解决；决心", "re+solve(松)", "resolve a conflict", "They resolved the dispute.", "他们解决了争端。"],
["resource", "/rɪˈsɔːs/", "n. 资源", "re+source(源)", "natural resources", "We waste resources.", "我们浪费资源。"],
["respond", "/rɪˈspɒnd/", "v. 回应", "re+spond(应)", "respond to", "She responded quickly.", "她很快回应了。"],
["restore", "/rɪˈstɔː/", "v. 恢复；修复", "re+store(立)", "restore order", "They restored the painting.", "他们修复了画作。"],
["restrain", "/rɪˈstreɪn/", "v. 抑制；约束", "re+strain(拉紧)", "restrain from", "He restrained his anger.", "他克制了怒气。"],
["restrict", "/rɪˈstrɪkt/", "v. 限制", "re+strict(束)", "restrict access", "Access is restricted.", "访问受限。"],
["retain", "/rɪˈteɪn/", "v. 保留", "re+tain(握)", "retain a memory", "We retained the staff.", "我们留住了员工。"],
["retreat", "/rɪˈtriːt/", "v./n. 撤退；静修", "re+treat(退)", "retreat from", "The army retreated.", "军队撤退了。"],
["retrive", "/rɪˈtriːv/", "v. 取回；检索", "re+trive(找)", "retrive data", "He retrieved the file.", "他取回了文件。"],
["reveal", "/rɪˈviːl/", "v. 揭示；透露", "re+veal(面纱)", "reveal the truth", "The data revealed a trend.", "数据揭示趋势。"],
["revenue", "/ˈrevənjuː/", "n. 收入；税收", "re+venue(来)", "tax revenue", "Revenue grew this year.", "今年收入增长。"],
["reverse", "/rɪˈvɜːs/", "v./adj. 反转(的)", "re+verse(转)", "in reverse", "The trend reversed.", "趋势反转了。"],
["revise", "/rɪˈvaɪz/", "v. 修订；复习", "re+vise(看)", "revise the draft", "Revise before the exam.", "考前复习。"],
["revive", "/rɪˈvaɪv/", "v.  revive；复苏", "re+vive(活)", "revive the economy", "The market revived.", "市场复苏了。"],
["revolve", "/rɪˈvɒlv/", "v. 旋转；围绕", "re+volv(滚)", "revolve around", "The debate revolves around it.", "辩论围绕它展开。"],
["reward", "/rɪˈwɔːd/", "n./v. 奖励", "re+ward(守)：回报看护", "a financial reward", "Hard work brings reward.", "努力带来回报。"],
["rigid", "/ˈrɪdʒɪd/", "adj. 僵硬的；严格的", "rig(硬)+id", "a rigid rule", "The schedule is rigid.", "日程很死板。"],
["rigorous", "/ˈrɪɡərəs/", "adj. 严格的；严密的", "rig(硬)+orous", "rigorous testing", "We need rigorous proof.", "我们需要严密证明。"],
["ritual", "/ˈrɪtʃuəl/", "n. 仪式；adj. 例行的", "rit(礼)+ual", "a daily ritual", "Coffee is my ritual.", "咖啡是我的日常仪式。"],
["robust", "/rəʊˈbʌst/", "adj. 强健的；稳健的", "rob(强)+ust", "a robust system", "The economy is robust.", "经济稳健。"],
["role", "/rəʊl/", "n. 角色；作用", "role 音似‘柔尔’", "play a role", "He plays a key role.", "他起关键作用。"],
["route", "/ruːt/", "n. 路线", "route 音似‘路特’", "the fastest route", "Take the scenic route.", "走风景线。"],
["routine", "/ruːˈtiːn/", "n. 日常；adj. 常规的", "route+ine", "a daily routine", "Keep a healthy routine.", "保持规律作息。"],
["rural", "/ˈrʊərəl/", "adj. 农村的", "rur(乡)+al", "rural areas", "Rural life is quiet.", "乡村生活安静。"],
["sacrifice", "/ˈsækrɪfaɪs/", "n./v. 牺牲", "sacr(圣)+fic(做)+e", "sacrifice for", "He sacrificed his time.", "他牺牲了时间。"],
["safeguard", "/ˈseɪfɡɑːd/", "v./n. 保护", "safe+guard(卫)", "safeguard against", "We safeguard privacy.", "我们保护隐私。"],
["salary", "/ˈsæləri/", "n. 薪水", "sal(盐)+ary：古以盐代薪", "a monthly salary", "His salary rose.", "他薪水涨了。"],
["sample", "/ˈsɑːmpl/", "n. 样本；v. 取样", "sample 音似‘桑普’", "a random sample", "We sampled 100 users.", "我们抽样了100名用户。"],
["sanction", "/ˈsæŋkʃn/", "n./v. 制裁；批准", "sanct(圣)+ion", "impose sanctions", "They sanctioned the plan.", "他们批准了计划。"],
["satisfy", "/ˈsætɪsfaɪ/", "v. 使满意", "satis(足)+fy", "satisfy the need", "The result satisfied us.", "结果令我们满意。"],
["scale", "/skeɪl/", "n. 规模；v. 缩放", "scale 音似‘斯盖尔’", "on a large scale", "We scaled the business.", "我们扩大了业务。"],
["scatter", "/ˈskætə/", "v. 散播；分散", "scatter 音似‘斯卡特’", "scatter the seeds", "The wind scattered the papers.", "风把文件吹散了。"],
["scenario", "/səˈnɑːriəʊ/", "n. 情景；剧本", "scen(景)+ario", "a worst-case scenario", "Plan for each scenario.", "为每个情景做预案。"],
["schedule", "/ˈʃedjuːl/", "n. 日程；v. 安排", "schedule 音似‘谢纠’", "on schedule", "The train is on schedule.", "火车准点。"],
["scheme", "/skiːm/", "n. 计划；v. 策划", "scheme 音似‘斯基姆’", "a clever scheme", "They schemed a fraud.", "他们策划了骗局。"],
["scope", "/skəʊp/", "n. 范围；v. 审视", "scope 音似‘斯扣普’", "beyond the scope", "This is out of scope.", "这超出范围。"],
["secure", "/sɪˈkjʊə/", "adj. 安全的；v. 获得", "se+cure(关)：关牢", "a secure job", "He secured the deal.", "他拿下了交易。"],
["segment", "/ˈseɡmənt/", "n. 部分；v. 分割", "seg(切)+ment", "a market segment", "We segment the users.", "我们给用户分群。"],
["select", "/sɪˈlekt/", "v. 选择；adj. 精选的", "se+lect(选)", "select carefully", "Select the best one.", "选最好的。"],
["sequence", "/ˈsiːkwəns/", "n. 顺序；v. 按序排", "sequ(跟)+ence", "in sequence", "Follow the sequence.", "按顺序来。"],
["series", "/ˈsɪəriːz/", "n. 系列", "ser(连)+ies", "a series of", "A series of events.", "一系列事件。"],
["settle", "/ˈsetl/", "v. 解决；定居", "set(定)+tle", "settle a dispute", "They settled the bill.", "他们结清了账单。"],
["severe", "/sɪˈvɪə/", "adj. 严重的；严厉的", "sever(严)+e", "a severe storm", "The penalty is severe.", "处罚严厉。"],
["shift", "/ʃɪft/", "v./n. 转移；轮班", "shift 音似‘_shift’", "a paradigm shift", "The shift was sudden.", "转变很突然。"],
["shortage", "/ˈʃɔːtɪdʒ/", "n. 短缺", "short(短)+age", "a labor shortage", "There is a water shortage.", "水资源短缺。"],
["significant", "/sɪɡˈnɪfɪkənt/", "adj. 重要的；显著的", "sign(记号)+i+fic(做)+ant", "a significant change", "There was significant growth.", "增长显著。"],
["similar", "/ˈsɪmələ/", "adj. 相似的", "simil(同)+ar", "be similar to", "The cases are similar.", "案例相似。"],
["simultaneous", "/ˌsɪmlˈteɪniəs/", "adj. 同时的", "simul(同)+taneous", "simultaneous translation", "同声传译即同步翻译。"],
["skeptical", "/ˈskeptɪkl/", "adj. 怀疑的", "skept(疑)+ical", "be skeptical of", "I am skeptical about it.", "我对此怀疑。"],
["skilled", "/skɪld/", "adj. 熟练的", "skill+ed", "a skilled worker", "We need skilled staff.", "我们需要熟练工。"],
["slump", "/slʌmp/", "n./v. 暴跌；萧条", "slump 音似‘斯兰普’", "a sales slump", "The market slumped.", "市场暴跌。"],
["soar", "/sɔː/", "v. 飙升", "soar 音似‘索尔’", "prices soar", "Costs soared overnight.", "成本一夜飙升。"],
["social", "/ˈsəʊʃl/", "adj. 社会的；社交的", "soci(同伴)+al", "social media", "He is social and outgoing.", "他外向爱社交。"],
["society", "/səˈsaɪəti/", "n. 社会", "soci(同伴)+ety", "a civil society", "Society is changing.", "社会在变。"],
["solar", "/ˈsəʊlə/", "adj. 太阳的", "sol(太阳)+ar", "solar energy", "Solar power is clean.", "太阳能很清洁。"],
["sole", "/səʊl/", "adj. 唯一的", "sole 音似‘搜尔’", "the sole owner", "He is the sole heir.", "他是唯一继承人。"],
["solid", "/ˈsɒlɪd/", "adj. 固体的；可靠的", "solid 音似‘搜lid’", "a solid argument", "We have solid evidence.", "我们有可靠证据。"],
["solve", "/sɒlv/", "v. 解决", "solv(松)", "solve a problem", "We solved the puzzle.", "我们解开了谜题。"],
["somewhat", "/ˈsʌmwɒt/", "adv. 有点", "some+what", "It is somewhat difficult.", "这有点难。"],
["source", "/sɔːs/", "n. 来源；v. 发起", "source 音似‘搜斯’", "from a reliable source", "Renewable sources matter.", "可再生能源很重要。"],
["spacious", "/ˈspeɪʃəs/", "adj. 宽敞的", "spaci(空间)+ous", "a spacious room", "The hall is spacious.", "大厅很宽敞。"],
["span", "/spæn/", "n. 跨度；v. 跨越", "span 音似‘斯潘’", "a time span", "The bridge spans the river.", "桥跨过河。"],
["spare", "/speə/", "adj. 备用的；v. 抽出", "spare 音似‘斯佩尔’", "spare no effort", "Spare some time.", "抽点时间。"],
["spatial", "/ˈspeɪʃl/", "adj. 空间的", "spati(空间)+al", "spatial awareness", "Children develop spatial sense.", "孩子发展空间感。"],
["specialize", "/ˈspeʃəlaɪz/", "v. 专攻", "special+ize", "specialize in", "He specializes in law.", "他专攻法律。"],
["species", "/ˈspiːʃiːz/", "n. 物种", "speci(种)+es", "an endangered species", "The species is dying out.", "该物种濒临灭绝。"],
["specific", "/spəˈsɪfɪk/", "adj. 具体的", "speci(种)+fic", "a specific example", "Give a specific case.", "给个具体案例。"],
["specify", "/ˈspesɪfaɪ/", "v. 明确说明", "speci(种)+fy", "specify the date", "Please specify the time.", "请明确时间。"],
["spectrum", "/ˈspektrəm/", "n. 光谱；范围", "spect(看)+rum", "a wide spectrum", "The spectrum of opinion.", "意见光谱很广。"],
["speculate", "/ˈspekjuleɪt/", "v. 推测；投机", "spec(看)+ulate", "speculate on", "They speculated about it.", "他们对此猜测。"],
["sphere", "/sfɪə/", "n. 球体；领域", "sphere 音似‘斯菲尔’", "in the public sphere", "It is in my sphere.", "这在我领域。"],
["spiritual", "/ˈspɪrɪtʃuəl/", "adj. 精神的", "spirit+ual", "spiritual needs", "Art meets spiritual needs.", "艺术满足精神需求。"],
["sponsor", "/ˈspɒnsə/", "n. 赞助者；v. 赞助", "spons(承诺)+or", "a corporate sponsor", "They sponsored the event.", "他们赞助了活动。"],
["stable", "/ˈsteɪbl/", "adj. 稳定的", "st(站)+able", "a stable economy", "The patient is stable.", "病人情况稳定。"],
["static", "/ˈstætɪk/", "adj. 静态的", "stat(站)+ic", "static prices", "The page is static.", "页面是静态的。"],
["statistic", "/stəˈtɪstɪk/", "n. 统计数字", "stat(站)+istic", "vital statistics", "The statistics are clear.", "数据很清楚。"],
["status", "/ˈsteɪtəs/", "n. 地位；状态", "stat(站)+us", "social status", "Check your order status.", "查订单状态。"],
["steady", "/ˈstedi/", "adj. 稳定的；v. 使稳固", "stead(立)+y", "a steady hand", "Progress is steady.", "进展平稳。"],
["stimulate", "/ˈstɪmjuleɪt/", "v. 刺激；激励", "stimul(刺)+ate", "stimulate growth", "The drug stimulates demand.", "药物刺激了需求。"],
["strategy", "/ˈstrætədʒi/", "n. 战略", "strat(军)+egy", "a clear strategy", "We need a strategy.", "我们需要战略。"],
["strength", "/streŋθ/", "n. 力量；长处", "streng(强)+th", "a strength of", "Honesty is his strength.", "诚实是他的长处。"],
["stretch", "/stretʃ/", "v. 伸展；n. 一段", "stretch 音似‘斯坠驰’", "stretch a budget", "The road stretches on.", "路向前延伸。"],
["strict", "/strɪkt/", "adj. 严格的", "strict 音似‘斯坠kt’", "strict rules", "He is strict but fair.", "他严厉但公正。"],
["structural", "/ˈstrʌktʃərəl/", "adj. 结构的", "struct(建)+ural", "a structural problem", "There is a structural flaw.", "存在结构性缺陷。"],
["struggle", "/ˈstrʌɡl/", "v./n. 挣扎；奋斗", "struggle 音似‘斯抓够’", "struggle with", "He struggled to cope.", "他艰难应付。"],
["subject", "/ˈsʌbdʒɪkt/", "n. 主题；adj. 受制的", "sub+ject(投)", "a sensitive subject", "He is subject to rules.", "他受规则约束。"],
["submerge", "/səbˈmɜːdʒ/", "v. 淹没；潜入", "sub+merge(沉)", "submerge under", "The town was submerged.", "小镇被淹没。"],
["submit", "/səbˈmɪt/", "v. 提交；屈服", "sub+mit(送)", "submit a report", "Submit your form.", "提交你的表格。"],
["subsequent", "/ˈsʌbsɪkwənt/", "adj. 随后的", "sub+sequ(跟)+ent", "in subsequent years", "Subsequent events proved it.", "后续事件证实了。"],
["subsidy", "/ˈsʌbsədi/", "n. 补贴", "sub+sid(坐)+y：坐下帮衬", "a government subsidy", "The subsidy was cut.", "补贴被削减。"],
["substance", "/ˈsʌbstəns/", "n. 物质；实质", "sub+stance(站)：底层根基", "a chemical substance", "There is no substance to it.", "这毫无实质。"],
["substitute", "/ˈsʌbstɪtjuːt/", "v. 替代；n. 替补", "sub+stitute(站)", "substitute for", "Use oil as a substitute.", "用油代替。"],
["subtle", "/ˈsʌtl/", "adj. 微妙的", "subt(下)+le：藏在底下", "a subtle difference", "There is a subtle hint.", "有微妙的暗示。"],
["sufficient", "/səˈfɪʃnt/", "adj. 足够的", "suf+fici(做)+ent：做到够", "sufficient evidence", "We have sufficient proof.", "我们有充足证据。"],
["suggest", "/səˈdʒest/", "v. 建议；暗示", "sug+gest(带)", "suggest doing", "I suggest we wait.", "我建议等等。"],
["summary", "/ˈsʌməri/", "n. 摘要；adj. 概括的", "sum(总)+ary", "in summary", "Give a brief summary.", "做个简要总结。"],
["superficial", "/ˌsuːpəˈfɪʃl/", "adj. 表面的", "super(上)+fici(面)+al", "a superficial wound", "His knowledge is superficial.", "他知识肤浅。"],
["supplement", "/ˈsʌplɪment/", "n./v. 补充", "sup+ple(满)+ment", "a dietary supplement", "We supplemented the diet.", "我们补充了饮食。"],
["supply", "/səˈplaɪ/", "v./n. 供应", "sup+ply(满)", "supply chain", "Supply met demand.", "供给满足了需求。"],
["suppose", "/səˈpəʊz/", "v. 假设；认为", "sup+pose(放)", "suppose that...", "Suppose it is true.", "假设这是真的。"],
["supress", "/səˈpres/", "v. 压制；隐瞒", "sup+press(压)", "supress a revolt", "They suppressed the news.", "他们压下了消息。"],
["supreme", "/suːˈpriːm/", "adj. 最高的", "supr(上)+eme", "the supreme court", "The supreme court ruled.", "最高法院裁决了。"],
["surface", "/ˈsɜːfɪs/", "n. 表面；v. 浮出", "sur(上)+face(面)", "on the surface", "The issue surfaced later.", "问题后来浮出了。"],
["surge", "/sɜːdʒ/", "n./v. 激增；汹涌", "surge 音似‘斯者’", "a surge in demand", "The crowd surged forward.", "人群向前涌。"],
["surplus", "/ˈsɜːpləs/", "n. 过剩；adj. 多余的", "sur(上)+plus(满)", "a trade surplus", "There is a budget surplus.", "预算有盈余。"],
["surround", "/səˈraʊnd/", "v. 包围", "sur+round(圈)", "surround by", "The park is surrounded by trees.", "公园被树包围。"],
["survey", "/ˈsɜːveɪ/", "n./v. 调查；勘测", "sur+vey(看)", "conduct a survey", "They surveyed the land.", "他们勘测了土地。"],
["survive", "/səˈvaɪv/", "v. 幸存；存活", "sur+vive(活)", "survive the crisis", "Only a few survived.", "只有少数存活。"],
["suspect", "/səˈspekt/", "v. 怀疑；n. 嫌疑犯", "sus+pect(看)：斜眼看", "suspect foul play", "He is a suspect.", "他是嫌疑人。"],
["suspend", "/səˈspend/", "v. 暂停；悬挂", "sus+pend(挂)", "suspend a service", "The licence was suspended.", "执照被吊销。"],
["sustain", "/səˈsteɪn/", "v. 维持；支撑", "sus+tain(握)：从下托", "sustain growth", "The economy sustained growth.", "经济保持增长。"],
["swamp", "/swɒmp/", "n. 沼泽；v. 淹没", "swamp 音似‘斯沃姆普’", "be swamped with", "We were swamped with work.", "我们被工作淹没。"],
["symbol", "/ˈsɪmbl/", "n. 象征；符号", "sym(同)+bol(投)", "a symbol of", "The dove is a symbol of peace.", "鸽子是和平象征。"],
["symmetry", "/ˈsɪmətri/", "n. 对称", "sym+metry(量)", "perfect symmetry", "The design has symmetry.", "设计很对称。"],
["sympathetic", "/ˌsɪmpəˈθetɪk/", "adj. 同情的；赞同的", "sym+path(感)+etic", "be sympathetic to", "She was sympathetic.", "她表示同情。"],
["syndrome", "/ˈsɪndrəʊm/", "n. 综合征", "syn+drome(跑)：一起表现", "a medical syndrome", "He has a rare syndrome.", "他患有罕见综合征。"],
["system", "/ˈsɪstəm/", "n. 系统；制度", "sy+stem(站)：立在一起", "a legal system", "The system works.", "系统运转正常。"],
["tackle", "/ˈtækl/", "v. 处理；n. 装备", "tackle 音似‘泰叩’", "tackle a problem", "We tackled the issue.", "我们处理了问题。"],
["tactic", "/ˈtæktɪk/", "n. 战术；策略", "tact(触)+ic", "a negotiation tactic", "Use a soft tactic.", "用软策略。"],
["target", "/ˈtɑːɡɪt/", "n. 目标；v. 瞄准", "target 音似‘他给特’", "meet the target", "We hit the target.", "我们达成了目标。"],
["tariff", "/ˈtærɪf/", "n. 关税", "tariff 音似‘泰瑞夫’", "impose a tariff", "The tariff was raised.", "关税上调了。"],
["tempt", "/tempt/", "v. 引诱", "tempt 音似‘探普特’", "tempt to do", "Don't be tempted by it.", "别被它诱惑。"],
["tendency", "/ˈtendənsi/", "n. 倾向", "tend(趋向)+ency", "a growing tendency", "There is a tendency to delay.", "有拖延的倾向。"],
["tense", "/tens/", "adj. 紧张的；n. 时态", "tens(拉)+e", "a tense moment", "The room went tense.", "房间气氛紧张。"],
["terminal", "/ˈtɜːmɪnl/", "n. 终点；adj. 末期的", "termin(终)+al", "a bus terminal", "He is terminally ill.", "他病入膏肓。"],
["territory", "/ˈterətri/", "n. 领土；领域", "terr(地)+itory", "defend the territory", "Animals mark territory.", "动物标记领地。"],
["theory", "/ˈθɪəri/", "n. 理论", "theo(神/看)+ry：看透的说法", "in theory", "In theory it works.", "理论上可行。"],
["thereby", "/ˌðeəˈbaɪ/", "adv. 从而", "there+by", "Thereby solving it.", "从而解决了它。"],
["therefore", "/ˈðeəfɔː/", "adv. 因此", "there+fore", "Therefore we declined.", "因此我们拒绝了。"],
["thesis", "/ˈθiːsɪs/", "n. 论文；论点", "thes(放)+is", "a doctoral thesis", "She defended her thesis.", "她答辩了论文。"],
["thorough", "/ˈθʌrə/", "adj. 彻底的", "thorough 音似‘萨拉’", "a thorough check", "We did a thorough review.", "我们做了彻底审查。"],
["threat", "/θret/", "n. 威胁", "threat 音似‘斯瑞特’", "a real threat", "Climate is a threat.", "气候是威胁。"],
["threshold", "/ˈθreʃhəʊld/", "n. 门槛；临界", "thresh(踩)+old", "cross the threshold", "We crossed the threshold.", "我们跨过了门槛。"],
["thrive", "/θraɪv/", "v. 繁荣", "thrive 音似‘斯瑞夫’", "thrive on", "The business thrived.", "生意红火。"],
["throughout", "/θruːˈaʊt/", "prep./adv. 遍及", "through+out", "throughout the year", "It rained throughout.", "整年都在下雨。"],
["tolerate", "/ˈtɒləreɪt/", "v. 容忍", "toler(忍)+ate", "tolerate pain", "We tolerate no cheating.", "我们零容忍作弊。"],
["topic", "/ˈtɒpɪk/", "n. 话题", "top(地)+ic：放台面", "a hot topic", "This is a hot topic.", "这是热点话题。"],
["topple", "/ˈtɒpl/", "v. 推翻；倒塌", "top(顶)+ple", "topple a regime", "The statue toppled.", "雕像倒了。"],
["toxic", "/ˈtɒksɪk/", "adj. 有毒的", "tox(毒)+ic", "a toxic substance", "The air was toxic.", "空气有毒。"],
["trace", "/treɪs/", "n./v. 痕迹；追踪", "trace 音似‘吹斯’", "trace the source", "We traced the leak.", "我们追到了泄漏源。"],
["tradition", "/trəˈdɪʃn/", "n. 传统", "tra(转)+dit(给)+ion：传下", "a long tradition", "We keep the tradition.", "我们保留传统。"],
["traffic", "/ˈtræfɪk/", "n. 交通；v. 交易", "traffic 音似‘拽菲克’", "heavy traffic", "Traffic was heavy.", "交通拥堵。"],
["tragic", "/ˈtrædʒɪk/", "adj. 悲剧的", "trag(悲)+ic", "a tragic loss", "It was a tragic accident.", "那是惨痛的事故。"],
["trail", "/treɪl/", "n. 小径；v. 追踪", "trail 音似‘吹尔’", "a mountain trail", "The dog trailed him.", "狗跟着他。"],
["trajectory", "/trəˈdʒektəri/", "n. 轨迹", "tra+ject(投)+ory", "a career trajectory", "The trajectory is clear.", "轨迹清晰。"],
["transfer", "/trænsˈfɜː/", "v./n. 转移；调任", "trans+fer(带)", "transfer money", "He transferred to Beijing.", "他调到了北京。"],
["transform", "/trænsˈfɔːm/", "v. 使改观", "trans+form(形)", "transform the city", "Education transforms lives.", "教育改变命运。"],
["transit", "/ˈtrænzɪt/", "n. 运输；v. 经过", "trans+it(走)", "in transit", "The goods are in transit.", "货物在途。"],
["translate", "/trænsˈleɪt/", "v. 翻译", "trans+late(带)", "translate into", "Translate it to Chinese.", "把它译成中文。"],
["transmission", "/trænsˈmɪʃn/", "n. 传播；传输", "trans+miss(送)+ion", "data transmission", "The transmission failed.", "传输失败了。"],
["transparent", "/trænsˈpærənt/", "adj. 透明的", "trans+parent(显)", "a transparent process", "We want transparent rules.", "我们要透明的规则。"],
["transport", "/trænˈspɔːt/", "v./n. 运输", "trans+port(运)", "public transport", "Transport was disrupted.", "交通中断了。"],
["treasure", "/ˈtreʒə/", "n. 宝藏；v. 珍视", "treasure 音似‘揣热’", "a national treasure", "We treasure the memory.", "我们珍视这记忆。"],
["treaty", "/ˈtriːti/", "n. 条约", "treat(处理)+y", "sign a treaty", "They signed a peace treaty.", "他们签了和平条约。"],
["tremendous", "/trəˈmendəs/", "adj. 巨大的", "trem(抖)+endous：让人发抖", "a tremendous effort", "There was tremendous support.", "支持巨大。"],
["trend", "/trend/", "n. 趋势；v. 倾向", "trend 音似‘穿的’", "a clear trend", "The trend is upward.", "趋势向上。"],
["trial", "/ˈtraɪəl/", "n. 试验；审判", "tri(试)+al", "a clinical trial", "The trial was fair.", "审判很公正。"],
["trigger", "/ˈtrɪɡə/", "v. 引发；n. 扳机", "trigger 音似‘垂格’", "trigger a crisis", "The news triggered panic.", "消息引发了恐慌。"],
["triumph", "/ˈtraɪʌmf/", "n./v. 胜利", "triumph 音似‘揣阿姆夫’", "a great triumph", "They triumphed at last.", "他们终于胜利了。"],
["trivial", "/ˈtrɪviəl/", "adj. 琐碎的", "tri(三)+vi(路)+al：三岔口小事", "a trivial matter", "Don't sweat the trivial.", "别为琐事烦心。"],
["turbulent", "/ˈtɜːbjələnt/", "adj. 动荡的", "turb(乱)+ulent", "a turbulent period", "The sea was turbulent.", "海面波涛汹涌。"],
["turnover", "/ˈtɜːnəʊvə/", "n. 营业额；流动率", "turn+over", "staff turnover", "The turnover is high.", "人员流动率高。"],
["ultimate", "/ˈʌltɪmət/", "adj. 最终的", "ultim(末)+ate", "the ultimate goal", "This is the ultimate aim.", "这是最终目标。"],
["unanimous", "/juˈnænɪməs/", "adj. 一致的", "un(单)+anim(心)+ous", "a unanimous vote", "The decision was unanimous.", "决定一致通过。"],
["undergo", "/ˌʌndəˈɡəʊ/", "v. 经历", "under+go", "undergo changes", "The city underwent reform.", "城市经历了改革。"],
["underlie", "/ˌʌndəˈlaɪ/", "v. 构成…的基础", "under+lie(躺)", "underlie the theory", "Trust underlies it all.", "信任是一切的基础。"],
["underline", "/ˌʌndəˈlaɪn/", "v. 强调；在…下划线", "under+line", "underline the risk", "This underlines the need.", "这突显了必要性。"],
["undermine", "/ˌʌndəˈmaɪn/", "v. 削弱", "under+mine(挖)", "undermine confidence", "The scandal undermined trust.", "丑闻削弱了信任。"],
["undertake", "/ˌʌndəˈteɪk/", "v. 承担；着手", "under+take(拿)", "undertake a task", "He undertook the project.", "他承担了项目。"],
["undoubtedly", "/ʌnˈdaʊtɪdli/", "adv. 无疑", "un+doubt+ed+ly", "It is undoubtedly true.", "这毫无疑问是真的。"],
["unemployment", "/ˌʌnɪmˈplɔɪmənt/", "n. 失业", "un+employ+ment", "rising unemployment", "Unemployment is a worry.", "失业令人担忧。"],
["unexpected", "/ˌʌnɪkˈspektɪd/", "adj. 意外的", "un+expected", "an unexpected result", "The outcome was unexpected.", "结果出人意料。"],
["uniform", "/ˈjuːnɪfɔːm/", "adj. 统一的；n. 制服", "uni(一)+form(形)", "a uniform standard", "Wear your uniform.", "穿上制服。"],
["unilateral", "/ˌjuːnɪˈlætrəl/", "adj. 单边的", "uni(一)+later(边)+al", "a unilateral move", "The move was unilateral.", "行动是单边的。"],
["unique", "/juˈniːk/", "adj. 独特的", "uni(一)+que", "a unique chance", "Every person is unique.", "每个人都是独特的。"],
["universal", "/ˌjuːnɪˈvɜːsl/", "adj. 普遍的", "uni(一)+vers(转)+al", "a universal truth", "It is a universal value.", "这是普世价值。"],
["universe", "/ˈjuːnɪvɜːs/", "n. 宇宙", "uni(一)+vers(转)+e", "the whole universe", "We studied the universe.", "我们研究宇宙。"],
["unjust", "/ˌʌnˈdʒʌst/", "adj. 不公平的", "un+just", "an unjust law", "The verdict was unjust.", "判决不公。"],
["unlike", "/ʌnˈlaɪk/", "prep. 不像", "un+like", "Unlike his brother, he is calm.", "与他兄弟不同，他很沉静。"],
["update", "/ˌʌpˈdeɪt/", "v./n. 更新", "up+date", "update the app", "We updated the data.", "我们更新了数据。"],
["upgrade", "/ˌʌpˈɡreɪd/", "v./n. 升级", "up+grade", "upgrade the system", "We upgraded the server.", "我们升级了服务器。"],
["uphold", "/ʌpˈhəʊld/", "v. 维护；支持", "up+hold(持)", "uphold the law", "The court upheld it.", "法院维持了原判。"],
["upright", "/ˈʌpraɪt/", "adj./adv. 直立的", "up+right", "an upright posture", "He is an upright man.", "他是个正直的人。"],
["upset", "/ʌpˈset/", "v. 使心烦；adj. 沮丧的", "up+set(放)", "an upset stomach", "The news upset her.", "消息让她难过。"],
["upstream", "/ˌʌpˈstriːm/", "adv./adj. 上游的", "up+stream", "an upstream town", "They moved upstream.", "他们搬到了上游。"],
["urban", "/ˈɜːbən/", "adj. 城市的", "urb(城)+an", "urban planning", "Urban life is busy.", "城市生活忙碌。"],
["urge", "/ɜːdʒ/", "v. 催促；n. 冲动", "urge 音似‘尔居’", "urge sb to", "He urged caution.", "他力主谨慎。"],
["utility", "/juːˈtɪləti/", "n. 效用；公用事业", "util(用)+ity", "public utility", "A utility provides water.", "公用事业供水。"],
["utilize", "/ˈjuːtəlaɪz/", "v. 利用", "util(用)+ize", "utilize resources", "We utilized the data.", "我们利用了数据。"],
["utmost", "/ˈʌtməʊst/", "adj. 极度的；n. 极限", "ut(外)+most", "of the utmost importance", "Safety is of utmost importance.", "安全至关重要。"],
["vacant", "/ˈveɪkənt/", "adj. 空缺的；空的", "vac(空)+ant", "a vacant post", "The seat was vacant.", "座位空着。"],
["vaccine", "/ˈvæksiːn/", "n. 疫苗", "vacc(牛)+ine：牛痘源", "a COVID vaccine", "The vaccine works.", "疫苗有效。"],
["vague", "/veɪɡ/", "adj. 模糊的", "vague 音似‘危格’", "a vague memory", "His answer was vague.", "他的回答含糊。"],
["valid", "/ˈvælɪd/", "adj. 有效的；合理的", "val(强)+id", "a valid argument", "The ticket is valid.", "票有效。"],
["valuable", "/ˈvæljuəbl/", "adj. 有价值的", "value+able", "a valuable lesson", "Time is valuable.", "时间宝贵。"],
["vanish", "/ˈvænɪʃ/", "v. 消失", "van(空)+ish", "vanish into thin air", "The money vanished.", "钱凭空消失了。"],
["variable", "/ˈveəriəbl/", "adj. 可变的；n. 变量", "vari(变)+able", "a key variable", "Control the variables.", "控制变量。"],
["variation", "/ˌveəriˈeɪʃn/", "n. 变化；变体", "vari(变)+ation", "seasonal variation", "There is natural variation.", "存在自然变异。"],
["variety", "/vəˈraɪəti/", "n. 多样；种类", "vari(变)+ety", "a wide variety", "We offer variety.", "我们提供多样选择。"],
["various", "/ˈveəriəs/", "adj. 各种各样的", "vari(变)+ous", "for various reasons", "They left for various reasons.", "他们因各种原因离开。"],
["vast", "/vɑːst/", "adj. 广阔的", "vast 音似‘瓦斯特’", "a vast area", "The desert is vast.", "沙漠广阔。"],
["vehicle", "/ˈviːəkl/", "n. 交通工具；媒介", "veh(运)+icle", "a green vehicle", "Language is a vehicle.", "语言是载体。"],
["velocity", "/vəˈlɒsəti/", "n. 速度", "veloc(快)+ity", "high velocity", "The velocity increased.", "速度加快了。"],
["venture", "/ˈventʃə/", "n. 冒险；v. 敢于", "vent(来)+ure", "a bold venture", "They ventured abroad.", "他们冒险出海。"],
["verify", "/ˈverɪfaɪ/", "v. 核实", "ver(真)+ify", "verify the facts", "Please verify the data.", "请核实数据。"],
["versatile", "/ˈvɜːsətaɪl/", "adj. 多才的；多用的", "vers(转)+atile", "a versatile tool", "He is a versatile actor.", "他是多面手。"],
["version", "/ˈvɜːʃn/", "n. 版本", "vers(转)+ion", "the latest version", "Update to the new version.", "升级到新版本。"],
["via", "/ˈvaɪə/", "prep. 经由", "via 音似‘via’", "travel via Beijing", "Send it via email.", "用邮件发。"],
["viable", "/ˈvaɪəbl/", "adj. 可行的", "vi(活)+able：能活", "a viable option", "It is a viable plan.", "这是可行的计划。"],
["victim", "/ˈvɪktɪm/", "n. 受害者", "vict(胜)+im：被征服者", "a flood victim", "They aided the victims.", "他们援助了受害者。"],
["viewpoint", "/ˈvjuːpɔɪnt/", "n. 观点", "view+point", "from my viewpoint", "It offers a fresh viewpoint.", "它提供新视角。"],
["violate", "/ˈvaɪəleɪt/", "v. 违反", "viol(暴)+ate", "violate the rules", "They violated the treaty.", "他们违反了条约。"],
["violent", "/ˈvaɪələnt/", "adj. 暴力的", "viol(暴)+ent", "a violent storm", "The protest turned violent.", "抗议演变成暴力。"],
["virtual", "/ˈvɜːtʃuəl/", "adj. 虚拟的；实质的", "virtu(真)+al", "a virtual meeting", "The win was virtual.", "胜利实质已定。"],
["virtue", "/ˈvɜːtʃuː/", "n. 美德；优点", "virtu(真)+e", "by virtue of", "Honesty is a virtue.", "诚实是美德。"],
["visible", "/ˈvɪzəbl/", "adj. 可见的", "vis(看)+ible", "be visible to", "The star is visible.", "星星清晰可见。"],
["vision", "/ˈvɪʒn/", "n. 视力；愿景", "vis(看)+ion", "a clear vision", "She has a bold vision.", "她有宏大的愿景。"],
["visual", "/ˈvɪʒuəl/", "adj. 视觉的", "vis(看)+ual", "visual aids", "Use visual examples.", "用视觉化例子。"],
["vital", "/ˈvaɪtl/", "adj. 至关重要的", "vit(生命)+al", "vital information", "Sleep is vital.", "睡眠至关重要。"],
["vocabulary", "/vəˈkæbjələri/", "n. 词汇", "voc(说)+abulary", "a wide vocabulary", "Build your vocabulary.", "扩充词汇量。"],
["voluntary", "/ˈvɒləntri/", "adj. 自愿的", "vol(意)+untary", "voluntary work", "He does voluntary work.", "他做志愿工作。"],
["volunteer", "/ˌvɒlənˈtɪə/", "n. 志愿者；v. 自愿做", "vol(意)+unteer", "a volunteer group", "She volunteered to help.", "她自愿帮忙。"],
["voter", "/ˈvəʊtə/", "n. 选民", "vot(誓)+er", "young voters", "Mobilize the voters.", "动员选民。"],
["vulnerable", "/ˈvʌlnərəbl/", "adj. 脆弱的；易受伤的", "vulner(伤)+able", "vulnerable groups", "Children are vulnerable.", "儿童很脆弱。"],
["wage", "/weɪdʒ/", "n. 工资；v. 发动", "wage 音似‘威治’", "a living wage", "They waged a war.", "他们发动了战争。"],
["wander", "/ˈwɒndə/", "v. 漫游；走神", "wander 音似‘弯得’", "wander off", "His mind wandered.", "他走神了。"],
["wealth", "/welθ/", "n. 财富", "weal(好)+th", "personal wealth", "Health is true wealth.", "健康是真财富。"],
["welfare", "/ˈwelfeə/", "n. 福利；安康", "wel(好)+fare(行)", "social welfare", "The welfare system helps.", "福利制度有帮助。"],
["whereas", "/ˌweərˈæz/", "conj. 然而；鉴于", "where+as", "Whereas A did, B didn't.", "A做了而B没做。"],
["whereby", "/ˌweəˈbaɪ/", "adv. 借此", "where+by", "a system whereby...", "A plan whereby we win.", "一个让我们获胜的计划。"],
["whilst", "/waɪlst/", "conj. 当…时；虽然", "while+st", "Whilst reading, he slept.", "他看着看着睡着了。"],
["widespread", "/ˈwaɪdspred/", "adj. 广泛的", "wide+spread", "widespread support", "The view is widespread.", "这观点很普遍。"],
["wisdom", "/ˈwɪzdəm/", "n. 智慧", "wis(智)+dom", "the wisdom of age", "Experience brings wisdom.", "经验带来智慧。"],
["withdraw", "/wɪðˈdrɔː/", "v. 撤回；取(款)", "with+draw(拉)", "withdraw a claim", "He withdrew the money.", "他取了款。"],
["withhold", "/wɪðˈhəʊld/", "v. 拒绝给；隐瞒", "with+hold(持)", "withhold information", "They withheld the truth.", "他们隐瞒了真相。"],
["withstand", "/wɪðˈstænd/", "v. 经受住", "with+stand(站)", "withstand pressure", "The bridge withstood the storm.", "桥经受住了风暴。"],
["witness", "/ˈwɪtnəs/", "n. 目击者；v. 目击", "wit(知)+ness", "a key witness", "He witnessed the event.", "他目击了事件。"],
["workforce", "/ˈwɜːkfɔːs/", "n. 劳动力", "work+force", "a skilled workforce", "The workforce shrank.", "劳动力缩减了。"],
["workshop", "/ˈwɜːkʃɒp/", "n. 研讨会；工坊", "work+shop", "a writing workshop", "They held a workshop.", "他们办了研讨会。"],
["worthy", "/ˈwɜːði/", "adj. 值得的", "worth+y", "a worthy cause", "It is worthy of note.", "这值得注意。"],
["yield", "/jiːld/", "v. 产生；屈服；n. 产量", "yield 音似‘耶尔德’", "yield to pressure", "The field yielded crops.", "田地长出庄稼。"],
["youngster", "/ˈjʌŋstə/", "n. 年轻人", "young+ster", "a lively youngster", "The youngsters played.", "年轻人玩耍。"],
["zone", "/zəʊn/", "n. 区域；v. 划区", "zone 音似‘邹’", "a war zone", "They zoned the area.", "他们给区域划了线。"]
]

def main():
    b = json.load(io.open(BANK, encoding="utf-8"))
    existing = set(w.get("word", "").lower() for w in b)
    added = 0
    skipped = 0
    bad = [it for it in NEW_WORDS if len(it) != 7]
    if bad:
        print("!! 字段数不为7的条目（已跳过）:", len(bad))
        for it in bad:
            print("   ", it)
    for it in NEW_WORDS:
        if len(it) == 7:
            word, ipa, pos, story, tip, en, cn = it
        elif len(it) == 6:
            word, ipa, pos, story, en, cn = it
            tip = ""
        else:
            continue
        if word.lower() in existing:
            skipped += 1
            continue
        b.append({
            "word": word,
            "ipa": ipa,
            "pos": pos,
            "story": story,
            "tip": tip,
            "en": en,
            "cn": cn,
        })
        existing.add(word.lower())
        added += 1
    io.open(BANK, "w", encoding="utf-8").write(json.dumps(b, ensure_ascii=False, indent=1))
    print("新增词数: %d，跳过重复: %d，词库总数: %d" % (added, skipped, len(b)))

if __name__ == "__main__":
    main()
