#!/usr/bin/env python3
"""第九轮：把 wordEmoji 大幅扩到 3000+ 词（模块化生成 JS 规则数组）
输入：ielts/ielts_bank.json 全部词 + pos 中文释义
输出：打印一段可粘贴到 study.html 的 map 数组（按 word/pos 关键词归类，含多种兜底）
策略：三层
 1) 精配：具体实物/抽象语义逐一映射（几千条规则，多词义词取其一）
 2) 词缀/词性大类兜底：-tion/-ment/-ness->物品, -er/-or->人, adj 特征词->表情, vt 动作->动作
 3) 最终默认：按词性给 (n->📦, v->⚡, adj->🎨, adv->✨)，不漏统一书本
"""
import json, re, os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
bank = json.load(open(os.path.join(REPO, 'ielts', 'ielts_bank.json'), encoding='utf-8'))

# ---------- 精配规则：语义关键词(英文词 或 中文释义) -> emoji ----------
# 顺序即优先级，前面命中优先（具体 > 大类）
SEMANTIC = [
  # 自然/动物/植物
  (r'\b(bird|eagle|owl|pigeon|swallow)\b|鸟', '🐦'),
  (r'\b(cat|kitten)\b|猫', '🐱'),
  (r'\b(dog|puppy|canine)\b|狗', '🐶'),
  (r'\b(fish|salmon|tuna)\b|鱼', '🐟'),
  (r'\b(horse|equine)\b|马(?!上|克)', '🐴'),
  (r'\b(cow|cattle|bull|ox)\b|牛(?!顿)', '🐮'),
  (r'\b(pig|swine|hog)\b|猪', '🐷'),
  (r'\b(sheep|lamb|wool)\b|羊|羊毛', '🐑'),
  (r'\b(monkey|ape|primate)\b|猴|猿', '🐒'),
  (r'\b(lion|tiger|leopard|panther)\b|狮|虎|豹', '🐯'),
  (r'\b(bear|polar)\b|熊', '🐻'),
  (r'\b(elephant)\b|象', '🐘'),
  (r'\b(rabbit|hare|bunny)\b|兔', '🐰'),
  (r'\b(snake|serpent|cobra)\b|蛇', '🐍'),
  (r'\b(frog|toad)\b|蛙|蟾', '🐸'),
  (r'\b(whale|dolphin)\b|鲸|海豚', '🐬'),
  (r'\b(butterfly)\b|蝴蝶', '🦋'),
  (r'\b(bee|honey)\b|蜜蜂|蜂蜜', '🐝'),
  (r'\b(ant)\b|蚂蚁', '🐜'),
  (r'\b(spider)\b|蜘蛛', '🕷️'),
  (r'\b(crab|lobster|shrimp)\b|蟹|虾', '🦀'),
  (r'\b(snail|slug)\b|蜗牛|蛞蝓', '🐌'),
  (r'\b(turtle|tortoise)\b|龟', '🐢'),
  (r'\b(crocodile|alligator)\b|鳄鱼', '🐊'),
  (r'\b(penguin)\b|企鹅', '🐧'),
  (r'\b(kangaroo)\b|袋鼠', '🦘'),
  (r'\b(koala)\b|考拉', '🐨'),
  (r'\b(mouse|rat|rodent)\b|鼠', '🐭'),
  (r'\b(tree|forest|woodland|oak|pine)\b|树|森林', '🌳'),
  (r'\b(flower|bloom|blossom|petal|rose|tulip)\b|花|开花|玫瑰', '🌸'),
  (r'\b(grass|lawn|meadow)\b|草|草坪|草地', '🌿'),
  (r'\b(leaf|foliage)\b|叶', '🍃'),
  (r'\b(fruit|fruit)\b|水果', '🍎'),
  (r'\b(apple)\b|苹果', '🍎'),
  (r'\b(banana)\b|香蕉', '🍌'),
  (r'\b(orange|citrus)\b|橙子|柑橘', '🍊'),
  (r'\b(grape)\b|葡萄', '🍇'),
  (r'\b(strawberry)\b|草莓', '🍓'),
  (r'\b(peach|lemon|mango|pineapple|watermelon|cherry)\b|桃|柠檬|芒果|菠萝|西瓜|樱桃', '🍉'),
  (r'\b(vegetable|carrot|potato|tomato|onion|cabbage|broccoli|cucumber)\b|蔬菜|胡萝卜|土豆|番茄|洋葱|白菜|西兰花|黄瓜', '🥦'),
  (r'\b(corn|maize|wheat|grain|rice|cereal)\b|玉米|小麦|谷物|大米|稻', '🌾'),
  (r'\b(nut|peanut|walnut|almond)\b|坚果|花生|核桃', '🥜'),
  (r'\b(mushroom|fungus)\b|蘑菇|真菌', '🍄'),
  # 天气/自然现象
  (r'\b(rain|rainy|rainfall|drizzle|downpour)\b|雨|降雨', '🌧️'),
  (r'\b(snow|snowy|blizzard|snowfall)\b|雪', '❄️'),
  (r'\b(wind|windy|breeze|gust|gale)\b|风', '🌬️'),
  (r'\b(cloud|cloudy|overcast)\b|云', '☁️'),
  (r'\b(storm|thunder|lightning|thunderstorm)\b|风暴|雷|闪电', '⛈️'),
  (r'\b(rainbow)\b|彩虹', '🌈'),
  (r'\b(sun|sunny|sunlight|sunshine)\b|太阳|阳光|晴朗', '☀️'),
  (r'\b(moon|lunar)\b|月亮|月球', '🌙'),
  (r'\b(star|starry|astronomy)\b|星星|星', '⭐'),
  (r'\b(rainbow)\b', '🌈'),
  (r'\b(fog|smog|mist|haze|foggy)\b|雾|霾', '🌫️'),
  (r'\b(flood|flooding)\b|洪水', '🌊'),
  (r'\b(drought)\b|干旱', '🏜️'),
  (r'\b(earthquake|quake|seismic)\b|地震', '🌍'),
  (r'\b(volcano|volcanic|eruption|lava)\b|火山|熔岩|喷发', '🌋'),
  (r'\b(tsunami)\b|海啸', '🌊'),
  (r'\b(ice|glacier|frozen|frost)\b|冰|冰川|霜', '🧊'),
  (r'\b(fire|flame|burning|combust)\b|火|火焰|燃烧', '🔥'),
  (r'\b(water|ocean|sea|river|lake|pond|stream)\b|水|海洋|大海|河流|湖', '💧'),
  (r'\b(wave)\b|波浪|浪潮', '🌊'),
  (r'\b(desert|arid)\b|沙漠|干旱', '🏜️'),
  (r'\b(island)\b|岛', '🏝️'),
  (r'\b(mountain|mount|peak|summit|ridge)\b|山|山峰|山顶|山脉', '⛰️'),
  (r'\b(hill)\b|丘陵|小山', '⛰️'),
  (r'\b(beach|shore|coast|seaside)\b|海滩|海岸|海滨', '🏖️'),
  # 食物
  (r'\b(bread|toast)\b|面包', '🍞'),
  (r'\b(cake|cookie|biscuit|pastry)\b|蛋糕|饼干|点心', '🍰'),
  (r'\b(milk|dairy|cheese|yogurt|butter)\b|牛奶|奶酪|酸奶|黄油', '🥛'),
  (r'\b(egg)\b|鸡蛋|蛋', '🥚'),
  (r'\b(meat|beef|pork|lamb|chicken|sausage)\b|肉|牛肉|猪肉|鸡肉|香肠', '🍖'),
  (r'\b(pizza)\b|披萨', '🍕'),
  (r'\b(noodle|pasta|spaghetti)\b|面|面条|意面', '🍝'),
  (r'\b(rice)\b|米饭', '🍚'),
  (r'\b(soup|stew)\b|汤|炖', '🍲'),
  (r'\b(salad)\b|沙拉', '🥗'),
  (r'\b(sandwich|burger|hamburger|hotdog)\b|三明治|汉堡|热狗', '🍔'),
  (r'\b(sushi)\b|寿司', '🍣'),
  (r'\b(curry|spice|spicy)\b|咖喱|香料|辣', '🍛'),
  (r'\b(sweet|sugar|candy|dessert|chocolate)\b|甜|糖|糖果|甜点|巧克力', '🍬'),
  (r'\b(coffee)\b|咖啡', '☕'),
  (r'\b(tea|green tea)\b|茶', '🍵'),
  (r'\b(juice)\b|果汁', '🧃'),
  (r'\b(wine|alcohol|beer|whisky|liquor|drunk|intoxicat)\b|酒|酒精|啤酒|威士忌|醉', '🍷'),
  (r'\b(water)\b|水', '🥤'),
  # 动物行为/生理
  (r'\b(sleep|asleep|nap|sleepy)\b|睡眠|睡觉|困', '😴'),
  (r'\b(eat|eating|consume|diet|nutrition)\b|吃|饮食|营养|摄入', '🍽️'),
  (r'\b(drink)\b|喝|饮用', '🥤'),
  (r'\b(run|running|jog|sprint)\b|跑步|奔跑|慢跑', '🏃'),
  (r'\b(walk|walking|stroll|pedestrian)\b|走|步行|散步', '🚶'),
  (r'\b(jump|leap|hop|bounce)\b|跳|跳跃|弹', '🦘'),
  (r'\b(swim|swimming)\b|游泳', '🏊'),
  (r'\b(fly|flying|flight)\b|飞|飞行', '✈️'),
  (r'\b(climb|climbing)\b|爬|攀登', '🧗'),
  (r'\b(dance|dancing)\b|跳舞|舞蹈', '💃'),
  (r'\b(sing|singing|song|vocal)\b|唱歌|歌曲|演唱', '🎤'),
  (r'\b(cry|weep|sob|tear)\b|哭泣|流泪|哭', '😢'),
  (r'\b(laugh|smile|funny|humor|amuse|joy|cheer)\b|笑|开心|滑稽|幽默|欢乐|愉快', '😄'),
  (r'\b(angry|anger|rage|furious|annoy|frustrat)\b|生气|愤怒|恼火|烦躁', '😠'),
  (r'\b(afraid|fear|scared|terrify|frighten|panic)\b|害怕|恐惧|恐慌|惊吓', '😨'),
  (r'\b(surprise|surprised|amaze|astonish|shock)\b|惊讶|吃惊|震惊', '😲'),
  (r'\b(sad|sadness|sorrow|grief|depress|gloom|melanchol)\b|悲伤|难过|忧郁|沮丧', '😞'),
  (r'\b(happy|happiness|delight|pleasure|satisfaction)\b|幸福|高兴|愉悦|满意', '😊'),
  (r'\b(love|like|affection|romantic|passion|fond|adore)\b|爱|喜欢|关爱|热情|浪漫', '❤️'),
  (r'\b(hate|hatred|dislike|loathe|hostil)\b|恨|讨厌|厌恶|敌意', '💔'),
  (r'\b(worry|anxious|anxiety|nervous|stress|tension)\b|担心|焦虑|紧张|压力', '😟'),
  (r'\b(excit|thrill|enthusiast|eager|passionat)\b|兴奋|激动|热情|热切', '🤩'),
  (r'\b(tired|fatigue|exhaust|weary|drowsy)\b|累|疲劳|疲惫|困乏', '🥱'),
  (r'\b(proud|pride)\b|骄傲|自豪', '😌'),
  (r'\b(shy|shame|embarrass|timid)\b|害羞|羞愧|尴尬|怯懦', '😳'),
  (r'\b(jealous|envy|envious|envious)\b|嫉妒|羡慕', '😒'),
  (r'\b(calm|peace|relax|tranquil|serene|quiet|gentle)\b|平静|放松|宁静|安静|温和', '😌'),
  (r'\b(confuse|confused|puzzle|bewilder)\b|困惑|迷惑|糊涂', '😕'),
  (r'\b(disappoint|let join|letdown|frustrate)\b|失望', '😔'),
  (r'\b(boring|bored|tedious|dull|monoton)\b|无聊|枯燥|乏味', '🥱'),
  # 人/职业/身份
  (r'\b(teacher|educator|instructor|professor|tutor|mentor)\b|老师|教师|教授|导师', '👨‍🏫'),
  (r'\b(student|pupil|learner|undergraduate)\b|学生|学员|本科生', '🎓'),
  (r'\b(doctor|physician|surgeon|medical)\b|医生|医师|外科', '👨‍⚕️'),
  (r'\b(nurse)\b|护士', '👩‍⚕️'),
  (r'\b(lawyer|attorney|counsel|legal)\b|律师|法律|法庭', '⚖️'),
  (r'\b(judge)\b|法官|裁判', '⚖️'),
  (r'\b(police|officer|cop)\b|警察|警官', '👮'),
  (r'\b(soldier|army|military|warrior|troop|battle|war)\b|士兵|军队|军人|战斗|战争', '🎖️'),
  (r'\b(farmer|agriculture|agricultural)\b|农民|农业', '👨‍🌾'),
  (r'\b(cook|chef|cooking|kitchen)\b|厨师|烹饪|厨房', '👨‍🍳'),
  (r'\b(driver|driving)\b|司机|驾驶', '🚗'),
  (r'\b(artist|painter|drawing|sketch|artistic)\b|艺术家|画家|绘画|素描', '🎨'),
  (r'\b(musician|music|instrument|piano|guitar|violin|melody|symphony)\b|音乐|乐器|钢琴|吉他|小提琴|旋律', '🎵'),
  (r'\b(singer)\b|歌手', '🎤'),
  (r'\b(actor|actress|film|movie|cinema|drama|theatre|stage)\b|演员|电影|剧院|舞台|戏剧', '🎬'),
  (r'\b(writer|author|author|literature|novel|poem|poetry|essay)\b|作家|作者|文学|小说|诗|散文', '✍️'),
  (r'\b(journalist|reporter|news|media|press)\b|记者|新闻|媒体', '📰'),
  (r'\b(scientist|research|laboratory|experiment|experimental)\b|科学家|研究|实验室|实验', '🔬'),
  (r'\b(engineer|engineering|technical|mechanical)\b|工程师|工程|机械', '⚙️'),
  (r'\b(business|entrepreneur|commerce|commercial|trade|merchant|enterprise)\b|商业|做生意|商人|企业|贸易', '💼'),
  (r'\b(banker|finance|financial|investment|stock)\b|银行家|金融|投资|股票', '💰'),
  (r'\b(athlete|sport|sports|exercise|training|gym|fitness)\b|运动员|运动|锻炼|健身|训练', '🏋️'),
  (r'\b(player|game|playing|soccer|football|basketball|tennis|match|team|competition)\b|球员|游戏|比赛|足球|篮球|网球|团队|竞赛', '⚽'),
  (r'\b(king|queen|prince|princess|royal|emperor|empire|noble|monarch|dynasty)\b|国王|女王|王子|公主|皇室|皇帝|帝国|贵族|王朝', '👑'),
  # 物品/日常
  (r'\b(house|home|building|apartment|residence|dwelling)\b|房子|房屋|家|住宅|建筑|公寓', '🏠'),
  (r'\b(school|classroom|college|university|campus|education)\b|学校|教室|大学|校园|教育', '🏫'),
  (r'\b(hospital|clinic|care)\b|医院|诊所', '🏥'),
  (r'\b(bank)\b(?!note)|银行', '🏦'),
  (r'\b(shop|store|mall|market|shopping|retail|supermarket)\b|商店|商场|超市|购物|零售|市场', '🛒'),
  (r'\b(restaurant|cafe|café|dining|meal|dinner|lunch|breakfast)\b|餐厅|咖啡馆|就餐|早餐|午餐|晚餐', '🍽️'),
  (r'\b(car|vehicle|auto|automobile|truck|bus|taxi)\b|汽车|车辆|卡车|公交车|出租车', '🚗'),
  (r'\b(train|railway|rail|subway|metro|locomotive)\b|火车|铁路|地铁', '🚆'),
  (r'\b(plane|airplane|aircraft|aviation|flight)\b|飞机|航空', '✈️'),
  (r'\b(ship|boat|vessel|sail|port|harbor)\b|船|轮船|帆船|港口', '🚢'),
  (r'\b(bicycle|bike|cycle)\b|自行车|单车', '🚲'),
  (r'\b(motorcycle|motorbike)\b|摩托车', '🏍️'),
  (r'\b(phone|telephone|cellphone|smartphone|mobile)\b|电话|手机|移动', '📱'),
  (r'\b(computer|laptop|computer|desktop|software|program|programming|coding)\b|电脑|计算机|软件|程序|编程', '💻'),
  (r'\b(internet|online|web|network|website|digital)\b|互联网|网络|在线|网站|数字', '🌐'),
  (r'\b(email|mail|letter|post)\b|邮件|信|邮政', '✉️'),
  (r'\b(book|textbook|magazine|library|reading|read)\b|书|课本|杂志|图书馆|阅读', '📚'),
  (r'\b(newspaper)\b|报纸', '📰'),
  (r'\b(television|tv|broadcast)\b|电视|广播', '📺'),
  (r'\b(radio)\b|收音机', '📻'),
  (r'\b(camera|photograph|photo|photography|picture)\b|相机|照片|摄影|图片', '📷'),
  (r'\b(clock|watch|time|temporal)\b|钟|手表|时间|计时', '⏰'),
  (r'\b(calendar|date)\b|日历|日期', '📅'),
  (r'\b(pen|pencil|notebook|paper|document|stationery)\b|笔|铅笔|笔记本|纸|文件', '📝'),
  (r'\b(key)\b(?!note)|钥匙|钥匙', '🔑'),
  (r'\b(lock|locked|security)\b|锁|安全', '🔒'),
  (r'\b(message|note|note)\b|消息|短信|便条', '💬'),
  (r'\b(light|lamp|electric|electricity|power|energy)\b|灯|光|电|电力|能源', '💡'),
  (r'\b(battery)\b|电池', '🔋'),
  (r'\b(bag|backpack|suitcase|luggage|pocket)\b|包|背包|行李箱|口袋', '🎒'),
  (r'\b(umbrella|raincoat)\b|雨伞|雨衣', '☂️'),
  (r'\b(shoe|sneaker|boot|footwear|slipper)\b|鞋|运动鞋|靴子|拖鞋', '👟'),
  (r'\b(clothes|clothing|dress|shirt|coat|jacket|jeans|skirt|fashion|wear)\b|衣服|服装|裙子|衬衫|外套|牛仔|时尚|穿戴', '👕'),
  (r'\b(hat|cap)\b|帽子', '🎩'),
  (r'\b(glasses|spectacles)\b|眼镜', '👓'),
  (r'\b(ring|jewelry|jewel|diamond|necklace)\b|戒指|珠宝|钻石|项链', '💍'),
  (r'\b(gift|present|prize|award|bonus|reward)\b|礼物|奖品|奖励|奖金', '🎁'),
  (r'\b(ticket)\b|票|门票', '🎫'),
  (r'\b(map)\b|地图', '🗺️'),
  (r'\b(cup|glass|mug|bottle|container)\b|杯子|玻璃杯|瓶子|容器', '🥛'),
  (r'\b(plate|bowl|dish)\b|盘子|碗|碟子', '🍽️'),
  (r'\b(knife|fork|spoon|cutlery)\b|刀|叉|勺子|餐具', '🍴'),
  (r'\b(bed|bedroom|sleeping)\b|床|卧室', '🛏️'),
  (r'\b(chair|desk|table|furniture|sofa|bench)\b|椅子|桌子|家具|沙发', '🪑'),
  (r'\b(door|entrance|gate|exit)\b|门|入口|出口', '🚪'),
  (r'\b(window)\b|窗户', '🪟'),
  (r'\b(road|street|path|highway|route|journey|trip|travel|tour|tourism)\b|路|街道|小路|公路|路线|旅程|旅行|旅游', '🛤️'),
  (r'\b(bridge)\b|桥', '🌉'),
  (r'\b(park|garden|yard|playground)\b|公园|花园|庭院|游乐场', '🏞️'),
  (r'\b(city|urban|town|village|capital)\b|城市|城镇|村庄|首都', '🏙️'),
  (r'\b(country|nation|national|state|region|rural)\b|国家|乡村|农村|地区', '🗾'),
  (r'\b(border|boundary|frontier|edge)\b|边界|边境|边缘', '↔️'),
  (r'\b(flag)\b|旗帜|国旗', '🚩'),
  (r'\b(fire|flame|burn)\b|火|火焰|燃烧', '🔥'),
  (r'\b(water|ocean|sea|river)\b|水|大海|河流', '💧'),
  (r'\b(glass|glassy)\b|玻璃', '🥃'),
  (r'\b(stone|rock|mineral)\b|石头|岩石|矿物', '🪨'),
  (r'\b(sand|sandy)\b|沙子|沙', '🏖️'),
  (r'\b(metal|iron|steel|gold|silver|copper)\b|金属|铁|钢|黄金|银|铜', '⚙️'),
  (r'\b(wood|wooden|timber)\b|木头|木材|木质', '🪵'),
  (r'\b(plastic)\b|塑料', '🧴'),
  (r'\b(paper)\b|纸', '📄'),
  (r'\b(cloth|fabric|cotton|silk|wool)\b|布|织物|棉|丝绸', '🧵'),
  (r'\b(paint|color|colour|dye|pigment)\b|颜料|颜色|染色', '🎨'),
  # 抽象/动作
  (r'\b(think|thought|consider|contemplate|ponder|mind|idea|concept)\b|思考|想法|概念|考虑|思想', '🤔'),
  (r'\b(learn|learning|study|study)\b|学习|学', '📖'),
  (r'\b(teach|teaching|educate|instruct)\b|教|教授|教导', '👨‍🏫'),
  (r'\b(know|knowing|knowledge|understand|understanding)\b|知道|理解|了解|知识', '🧠'),
  (r'\b(remember|recall|memorize|memory)\b|记住|回忆|记忆', '🧠'),
  (r'\b(forget|forget)\b|忘记', '😵'),
  (r'\b(speak|speech|talk|say|tell|conversation|communicate|communication|language|discuss)|说话|谈话|沟通|交流|语言', '🗣️'),
  (r'\b(listen|hearing|listen)\b|听|听力', '👂'),
  (r'\b(see|seeing|view|look|watch|observe|vision|visual)\b|看|看到|观察|视觉|注视', '👀'),
  (r'\b(write|writing|word|vocabulary|spelling|text|typing|type)\b|写|写作|单词|词汇|拼写|文字|打字', '✍️'),
  (r'\b(read|reading|literacy)\b|阅读|认读', '📖'),
  (r'\b(buy|purchase|shop|pay|cost|spend|expense|price|worth)\b|买|购买|支付|花费|价格|价值|费用', '💳'),
  (r'\b(sell|sale|market|merchandise|profit)\b|卖|销售|利润', '💰'),
  (r'\b(money|cash|currency|salary|wage|income)\b|钱|现金|货币|工资|收入|薪水', '💵'),
  (r'\b(budget|save|saving|finance|economy|economic|wealth|rich|fortune)\b|预算|节省|节约|经济|财富|富有|有钱', '💲'),
  (r'\b(borrow|lend|loan|debt|owe)\b|借|贷款|债务|欠', '🏦'),
  (r'\b(work|working|job|labor|employment|profession|career|task|duty)\b|工作|职业|劳动|任务|职责|就业', '💼'),
  (r'\b(rest|break|relax|leisure|holiday|vacation|weekend)\b|休息|放松|休闲|假期|周末|度假', '🏖️'),
  (r'\b(go|move|move|motion|movement|travel|travel)\b|去|移动|运动|旅行', '➡️'),
  (r'\b(come|arrive|return|reach)\b|来|到达|返回|到达', '↩️'),
  (r'\b(give|offer|provide|supply|provide)\b|给|提供|给予|供给', '🤲'),
  (r'\b(get|obtain|gain|acquire|receive|attain|achieve)\b|得到|获得|取得|达到|获取', '🎯'),
  (r'\b(make|create|produce|build|construct|manufacture|generate|fabricate)\b|做|制作|创造|生产|建造|制造|产生', '🛠️'),
  (r'\b(change|change|alter|modify|transform|shift|vary|convert|adjust|adapt)\b|改变|变化|修改|转换|转变|调整|适应', '🔄'),
  (r'\b(improve|improvement|enhance|develop|development|progress|advance|boost|upgrade)\b|改进|提高|提升|发展|进步|增强|升级', '📈'),
  (r'\b(reduce|decrease|decline|lower|diminish|cut|shrink|less|minimize)\b|减少|降低|下降|缩减|变小|最小化', '📉'),
  (r'\b(increase|rise|grow|growth|expand|extend|add|boost|augment|raise)\b|增加|增长|上升|扩大|扩张|提高|延长', '📈'),
  (r'\b(start|begin|commence|origin|initial|launch|establish|found|initiate)\b|开始|启动|发起|建立|创立|起源|最初', '🚀'),
  (r'\b(stop|end|finish|cease|complete|conclude|halt|terminate|abandon)\b|停止|结束|完成|终止|放弃', '⏹️'),
  (r'\b(help|help|aid|assist|support|facilitate|relief)\b|帮助|援助|支持|促进|救助', '🤝'),
  (r'\b(prevent|avoid|stop|hinder|block|obstruct|prohibit|ban|forbid)\b|防止|避免|阻止|阻碍|禁止|阻挡', '🚫'),
  (r'\b(allow|permit|enable|let)\b|允许|准许|使能够', '✅'),
  (r'\b(open|opening)\b|打开|开放|开启', '🔓'),
  (r'\b(close|closed|shut)\b|关闭|合上', '🔒'),
  (r'\b(success|succeed|successful|achievement|accomplish|victory|win|triumph)\b|成功|成就|胜利|赢|达成', '🏆'),
  (r'\b(fail|failure|fail|defeat|lose|setback)\b|失败|输|挫败|挫折', '❌'),
  (r'\b(problem|issue|challenge|difficulty|trouble|crisis|obstacle|hardship)\b|问题|困难|挑战|麻烦|危机|障碍|困境', '⚠️'),
  (r'\b(solve|solution|resolve|fix|repair|settle)\b|解决|方案|修复|修理|处理', '🔧'),
  (r'\b(choose|choice|select|select|elect|decide|decision|option|prefer|preference)\b|选择|挑选|决定|偏好|选项', '☑️'),
  (r'\b(compare|comparison|contrast|similar|same|equal|identical)\b|比较|对比|相似|相同|相等|一样', '⚖️'),
  (r'\b(differ|difference|different|distinguish|unique|distinct|vary|categorize|classify|classify)\b|不同|区别|区分|独特|分类', '🔀'),
  (r'\b(important|importance|significant|significant|crucial|vital|essential|key|major|critical)\b|重要|关键|至关重要|重大|必要', '⭐'),
  (r'\b(benefit|benefit|advantage|useful|helpful|valuable|worthwhile|profitable)\b|好处|优势|有用|有价值|有益', '👍'),
  (r'\b(danger|dangerous|risk|risky|hazard|threat|threaten|peril|lurking)\b|危险|风险|威胁|危害|隐患', '⚠️'),
  (r'\b(safety|safe|secure|security|safeguard|protection|protect|defend)\b|安全|保护|防御|保障', '🛡️'),
  (r'\b(health|healthy|fitness|wellness|medical|treat|treatment|recover|heal|cure)\b|健康|保健|治疗|康复|治愈', '💊'),
  (r'\b(ill|sick|disease|illness|symptom|infection|virus|bacteria|germ)\b|生病|疾病|症状|感染|病毒|细菌', '🤒'),
  (r'\b(pain|hurt|injury|injure|wound|ache|suffer)\b|疼痛|伤害|受伤|痛苦', '🤕'),
  (r'\b(save|rescue|safety|save)\b|拯救|营救|挽救', '🛟'),
  (r'\b(strong|strength|powerful|power|force|energy|vigor|sturdy|robust)\b|强|力量|强大|强壮|有力|能量', '💪'),
  (r'\b(weak|weakness|fragile|feeble|vulnerable)\b|弱|脆弱|虚弱|易受伤害', '🪫'),
  (r'\b(fast|speed|rapid|quick|swift|hurry|hasten|accelerate|accelerate)\b|快|迅速|速度|加速|赶紧', '⚡'),
  (r'\b(slow|slowly|delay|lag|postpone|put off|delayed)\b|慢|缓慢|延迟|推迟', '🐢'),
  (r'\b(new|novel|fresh|recent|modern|latest)\b|新|新颖|新鲜|最近|现代|最新', '🆕'),
  (r'\b(old|ancient|age|aged|elderly|senior|antique|outdated)\b|旧|古老|年老|年长|过时', '👴'),
  (r'\b(big|large|huge|giant|massive|enormous|vast|immense|grand|substantial)\b|大|巨大|庞大|宏大|庞大', '🐘'),
  (r'\b(small|little|tiny|minor|slight|miniature|modest|slender)\b|小|微小|少量|细小|轻微', '🐜'),
  (r'\b(long|length|cross|span)\b|长|长度|跨越', '📏'),
  (r'\b(short|brief|brief|concise|height)\b|短|简短|矮', '📐'),
  (r'\b(high|height|tall|elevated|altitude)\b|高|高度|海拔|高大', '⛰️'),
  (r'\b(deep|depth|profound)\b|深|深度|深刻', '🌊'),
  (r'\b(wide|broad|width|extensive)\b|宽|宽阔|广泛', '↔️'),
  (r'\b(narrow|tight)\b|窄|狭窄', '↔️'),
  (r'\b(heavy|weight|load|mass)\b|重|重量|负荷', '🏋️'),
  (r'\b(light|lighter|lightweight|weightless)\b|轻|轻盈', '🪶'),
  (r'\b(hot|heat|warm|temperature|thermal|scorching)\b|热|高温|温暖|热度', '🌡️'),
  (r'\b(cold|cool|chilly|freeze|chill)\b|冷|凉爽|寒冷|冰冻', '🥶'),
  (r'\b(wet|moist|damp|humidity|humid|drizzle)\b|湿|潮湿|湿润', '💦'),
  (r'\b(dry|dry|arid|drought)\b|干|干燥|干旱', '🏜️'),
  (r'\b(clean|clean|wash|purify|hygiene)\b|干净|清洁|洗涤|净化', '🧼'),
  (r'\b(dirty|mess|polluted|pollution|contaminate)\b|脏|污染|弄脏|污染', '💩'),
  (r'\b(beautiful|beauty|pretty|gorgeous|elegant|attractive|charm|lovely|handsome)\b|美丽|漂亮|优雅|迷人|英俊|可爱', '🌸'),
  (r'\b(ugly|hideous)\b|丑|难看', '👹'),
  (r'\b(rich|wealthy|wealth)\b|富裕|富有', '💰'),
  (r'\b(poor|poverty|impoverish)\b|穷|贫困|贫穷', '🪙'),
  (r'\b(free|liberty|freedom|independent|independence)\b|自由|独立|自主', '🕊️'),
  (r'\b(fair|justice|equal|equality|fairness|impartial)\b|公平|公正|平等', '⚖️'),
  (r'\b(correct|right|proper|accurate|accurate|precise|exact)\b|正确|准确|精确|恰当', '✔️'),
  (r'\b(wrong|false|error|mistake|bug|incorrect|inaccurate)\b|错误|不对|失误|差错', '❌'),
  (r'\b(true|truth|genuine|authentic|real|fact|honest|sincere)\b|真实|真正|诚实|真诚|事实', '💎'),
  (r'\b(fake|false|fraud|forgery|counterfeit|deceive|deceit|lie|loyal' +')\b|假|伪造|欺诈|欺骗|撒谎|虚假', '🃏'),
  (r'\b(beauty|beautiful)\b', '🌸'),
  (r'\b(hard|difficult|tough|challenging|arduous|rigorous)\b|难|困难|艰苦|费劲', '🧗'),
  (r'\b(easy|simple|easy|effortless|straightforward|facile)\b|容易|简单|轻松', '🟢'),
  (r'\b(possible|possibility|possible|feasible)\b|可能|可行性', '🤷'),
  (r'\b(impossible|impossibility|impossible)\b|不可能', '🚫'),
  (r'\b(sure|certain|definite|confident|convincing|determine)\b|确定|肯定|确信|有把握', '🎯'),
  (r'\b(uncertain|doubt|doubtful|ambiguous|vague|unclear|hesitant|hesitate)\b|不确定|怀疑|模糊|含糊|犹豫', '🤔'),
  (r'\b(together|joint|collaborate|cooperate|cooperation|collective|unite|unity|union|unified)\b|一起|合作|协作|联合|团结|统一', '🤝'),
  (r'\b(separate|apart|divide|div[ie]de|split|distinguish|isolate|segregate)\b|分开|分离|区分|分裂|隔离|孤立', '✂️'),
  (r'\b(best|better|greatest|top|excellent|outstanding|superior|remarkable|exceptional)\b|最好|最佳|优秀|出色|卓越|顶级', '🏅'),
  (r'\b(worst|terrible|awful|horrible|bad|dreadful)\b|最差|糟糕|可怕|恶劣|坏', '💀'),
  (r'\b(good|well|fine|great|nice|positive|favorable)\b|好|良好|不错|正面|有利', '😊'),
  (r'\b(bad|harm|harmful|damage|damage|negative|adverse|detrimental)\b|坏|有害|损害|负面|不利', '👎'),
  # 更多抽象高频
  (r'\b(agree|agreement|consent|approve|approval|accept)\b|同意|赞成|接受|认可', '👍'),
  (r'\b(disagree|disagreement|object|oppose|opposition|reject|refuse|deny)\b|不同意|反对|拒绝|否认|驳回', '👎'),
  (r'\b(explain|explain|describe|description|illustrate|define|definition|demonstrate)\b|解释|说明|描述|阐释|定义|演示', '💬'),
  (r'\b(discuss|discussion|debate|argue|argument|controversial|dispute|negotiate)\b|讨论|争论|辩论|争议|谈判', '⚖️'),
  (r'\b(believe|belief|faith|opinion|view|perspective|conviction|assume)\b|相信|信念|信仰|观点|视角|看法', '💭'),
  (r'\b(doubt)\b|疑问|怀疑', '❓'),
  (r'\b(question|ask|inquiry|query|enquiry)\b|问题|提问|询问|查询', '❓'),
  (r'\b(answer|reply|response|respond|reply)\b|回答|答复|回应|回复', '🗨️'),
  (r'\b(hope|wish|desire|expect|expectation|dream|aspiration|ambition)\b|希望|愿望|渴望|期待|梦想|抱负|野心', '🌠'),
  (r'\b(plan|planning|strategy|scheme|arrange|arrangement|schedule|organize|organize)\b|计划|方案|策略|安排|组织|日程|策划', '📋'),
  (r'\b(prepare|preparation|ready|get ready)\b|准备|预备|就绪', '🧳'),
  (r'\b(test|exam|exam|quiz|assessment|evaluate|evaluation|grade|score|mark)\b|测试|考试|测验|评估|打分|评分|成绩', '📝'),
  (r'\b(school)\b|学校', '🏫'),
  (r'\b(travel|travel|journey|trip|tour|visit|explore|exploration|adventure)\b|旅行|旅游|游览|探索|冒险', '🧭'),
  (r'\b(discover|discovery|find|invent|invention|explore)\b|发现|发明|探索|找到', '🔍'),
  (r'\b(search|look for|seek|hunt)\b|寻找|搜寻|搜索|寻找', '🔎'),
  (r'\b(show|display|exhibit|present|reveal|demonstrate)\b|展示|显示|呈现|揭示', '📽️'),
  (r'\b(hide|conceal|cover|secret|disguise)\b|隐藏|掩盖|秘密|伪装', '🙈'),
  (r'\b(wait|await|delay|postpone)\b|等待|等候|推迟', '⏳'),
  (r'\b(arrive|arrival|reach|land|depart|departure|leave|set off)\b|到达|抵达|离开|出发', '🛬'),
  (r'\b(enter|entry|enter)\b|进入|入口', '🚪'),
  (r'\b(exit|leave|depart|departure)\b|退出|离开', '🚪'),
  (r'\b(return|go back|come back)\b|返回|回来', '↩️'),
  (r'\b(use|usage|utilize|employ|apply|application|adopt)\b|使用|运用|应用|采用|利用', '🛠️'),
  (r'\b(need|require|requirement|demand|necessary|essential)\b|需要|要求|必要|必需', '🆘'),
  (r'\b(want|would like|desire)\b|想要|想要', '🙏'),
  (r'\b(can|could|able|ability|capability)\b|能力|能够|才能', '💪'),
  (r'\b(must|should|ought|oblig|duty|responsible|responsibility)\b|必须|应该|责任|义务', '📌'),
  (r'\b(may|might|perhaps|maybe|probably|likely|possibility)\b|也许|大概|或许|可能', '🤷'),
  (r'\b(always|often|usually|frequently|sometimes|rarely|seldom|never|customary|habit)\b|总是|经常|通常|偶尔|很少|从不|习惯', '🔁'),
  (r'\b(now|today|present|current|recent|modern)\b|现在|今天|当前|最近', '🕐'),
  (r'\b(past|previous|former|last)\b|过去|以前|先前', '⏪'),
  (r'\b(future|upcoming|coming|next|tomorrow)\b|未来|将来|明天|即将', '🔮'),
  (r'\b(early|late|on time|punctual|timely)\b|早|晚|准时|及时', '⏰'),
  (r'\b(day|daily|daytime)\b|天|白天|每日', '🌞'),
  (r'\b(night|nighttime|midnight|evening)\b|夜晚|晚上|深夜', '🌙'),
  (r'\b(week|month|year|annual|yearly|weekly|monthly|daily)\b|周|月|年|每年|每周|每月', '📆'),
  (r'\b(season|seasonal)\b|季节|季节性', '🍂'),
  (r'\b(spring|summer|autumn|winter|fall)\b|春天|夏天|秋天|冬天', '🍂'),
  (r'\b(negative)\b', '➖'),
  (r'\b(positive)\b', '➕'),
  # ---- 学术/抽象高频词（补足 15% 未命中）----
  (r'\b(rhetoric|allegory|metaphor|symbolize|symbolic|imagery)\b|修辞|寓言|隐喻|象征|意象', '🎭'),
  (r'\b(subtle|nuance|delicate|intricate|elaborate|refined)\b|微妙|细腻|精细|复杂微妙|精巧', '🧵'),
  (r'\b(manipulate|manipulation|control|influence|sway|exploit)\b|操纵|控制|影响|利用|支配', '🎮'),
  (r'\b(epidemic|pandemic|outbreak|plague|contagious|infectious)\b|流行病|疫情|爆发|传染病', '🦠'),
  (r'\b(acknowledge|acknowledgment|admit|concede|recognize|recognize)\b|承认|认可|确认|致谢', '🙋'),
  (r'\b(apparent|obvious|evident|evident|manifest|clear)\b|明显|显然|显而易见', '👁️'),
  (r'\b(bias|prejudice|biased|partial|favoritism)\b|偏见|偏颇|偏袒|成见', '🎭'),
  (r'\b(concurrent|simultaneous|parallel|coincide|synchronize)\b|同时|并发|并行|同步|巧合', '⏱️'),
  (r'\b(consolidate|consolidation|strengthen|reinforce|combine|merge|unify)\b|巩固|合并|联合|强化|统一', '🧱'),
  (r'\b(derive|derivation|originate|stem from|obtain from)\b|派生|源于|推导|获得', '🌱'),
  (r'\b(distribute|distribution|allocate|allot|dispense|spread|disseminate)\b|分配|分发|分布|传播', '📤'),
  (r'\b(exclude|exclusion|exclude|omit|eliminate|rule out)\b|排除|剔除|排除在外|省略', '🚫'),
  (r'\b(extract|extraction|remove|withdraw|pull out|elicit)\b|提取|提取|抽取|拔出|摘录', '🧪'),
  (r'\b(formulate|formulation|define|articulate|frame|conceive|devise|draft)\b|制定|阐述|构想|起草|表述', '📝'),
  (r'\b(hierarchy|hierarchical|rank|layered|pyramid)\b|等级|层级|层次|等级制度', '🏢'),
  (r'\b(incentive|motivation|motivate|stimulus|reward|encourage|encourage)\b|激励|动机|诱因|刺激|鼓励', '🎯'),
  (r'\b(incorporate|integrate|include|merge|embody|absorb|blend)\b|合并|纳入|整合|融合|吸收', '🧩'),
  (r'\b(indicate|indication|suggest|imply|signal|denote|signify|represent)\b|表明|暗示|指示|表示|显示', '💡'),
  (r'\b(interpret|interpretation|translate|explain|construe|decode|decipher)\b|解释|诠释|解读|翻译|理解', '📖'),
  (r'\b(legitimate|legitimacy|valid|justified|lawful|proper|authentic)\b|合法|正当|合理|有效|正统', '✅'),
  (r'\b(mediate|mediation|intervene|arbitrate|negotiate|broker)\b|调解|斡旋|仲裁|介入', '🤝'),
  (r'\b(perceive|perception|sense|detect|discern|realize|recognize)\b|感知|察觉|理解|辨别|领会', '👁️'),
  (r'\b(radical|extreme|drastic|profound|revolutionary|fundamental)\b|激进|激进|彻底|根本|革命性', '🔥'),
  (r'\b(random|randomly|arbitrary|haphazard|unsystematic)\b|随机|任意|随意', '🎲'),
  (r'\b(react|reaction|respond|reply|feedback|response)\b|反应|回应|反馈', '💥'),
  (r'\b(seminar|workshop|conference|symposium|lecture|lecture|tutorial)\b|研讨会|讲座|课程|研讨班', '🎓'),
  (r'\b(census|survey|poll|statistics|data|statistical|questionnaire)\b|人口普查|调查|统计|数据|问卷', '📊'),
  (r'\b(legislature|legislative|parliament|congress|senate|council|law|statute|policy|regulation)\b|立法|议会|国会|法律|政策|法规', '🏛️'),
  (r'\b(ecosystem|habitat|biodiversity|environment|ecological|sustainable)|生态系统|栖息地|生物多样性|环境|生态', '🌍'),
  (r'\b(landfill|waste|garbage|recycle|recycling|disposal|pollutant|emission)\b|垃圾|废物|回收|排放|污染|填埋', '♻️'),
  (r'\b(ozone|atmosphere|greenhouse|carbon|climate|glacier|emission)\b|臭氧|大气|温室|碳|气候|冰川', '🌫️'),
  (r'\b(algorithm|computation|computational|logic|logical|formula|syntax|code)\b|算法|计算|逻辑|公式|语法|代码', '🧮'),
  (r'\b(database|storage|data|record|archive|memory)\b|数据库|存储|数据|记录|存档', '🗃️'),
  (r'\b(virtual|simulate|simulation|digital|artificial|synthetic|simulate|simulation)\b|虚拟|模拟|仿真|数字化|合成', '🖥️'),
  (r'\b(prototype|model|sample|version|demo|blueprint|framework)\b|原型|模型|样板|版本|框架', '🧩'),
  (r'\b(constitute|constitution|establish|form|compose|comprise|represent)\b|构成|组成|建立|代表|组建', '🧱'),
  (r'\b(constrain|constraint|restrict|restriction|limit|limitation|confine|bound|restrain)\b|限制|约束|束缚|局限|约束', '⛓️'),
  (r'\b(culminate|culmination|climax|peak|apex|finalize)\b|达到顶点|高潮|顶峰|完成', '🏔️'),
  (r'\b(degrade|degradation|deteriorate|decline|worsen|deterioration)\b|退化|恶化|下降|变坏|降解', '📉'),
  (r'\b(deem|consider|regard|treat as|view as)\b|认为|视为|看作', '🤔'),
  (r'\b(deficit|deficiency|shortage|scarcity|lack|insufficient|inadequate)\b|赤字|短缺|缺乏|不足|匮乏', '📉'),
  (r'\b(demolish|demolition|destroy|tear down|raze|dismantle)\b|拆除|摧毁|破坏|瓦解', '💥'),
  (r'\b(depict|depiction|portray|illustrate|picture|characterize)\b|描绘|描绘|刻画|表现|描述', '🖼️'),
  (r'\b(designate|designation|appoint|assign|name|label|categorize)\b|指定|任命|指派|命名|归类', '🏷️'),
  (r'\b(detriment|detrimental|harmful|adverse|damaging|prejudicial)\b|损害|有害|不利|伤害', '👎'),
  (r'\b(deviate|deviation|diverge|depart|vary)\b|偏离|背离|偏差|出入', '↪️'),
  (r'\b(dimension|aspect|factor|element|component|perspective|facets)\b|维度|方面|因素|要素|角度', '🧊'),
  (r'\b(discrepancy|inconsistency|contradiction|mismatch|gap|difference)\b|差异|不一致|矛盾|出入|差距', '↔️'),
  (r'\b(discriminate|discrimination|distinguish|differentiate|segregate)\b|歧视|区分|辨别|划清界限', '⚖️'),
  (r'\b(displace|displacement|replace|relocate|substitute|shift)\b|取代|转移|替代|迁移', '🔄'),
  (r'\b(disseminate|distribution|spread|propagate|circulate|broadcast)\b|传播|散布|宣传|扩散', '📡'),
  (r'\b(elicit|evoke|provoke|trigger|generate|prompt|draw out)\b|引出|激起|触发|引发', '⚡'),
  (r'\b(emerge|emergence|appear|arise|surface|come about)\b|出现|浮现|兴起|显现', '🌅'),
  (r'\b(encompass|include|cover|comprise|embrace|contain|span)\b|包含|涵盖|包括|囊括', '🌐'),
  (r'\b(endorse|endorsement|approve|support|sanction|back|advocate)\b|支持|认可|拥护|背书|赞同', '👍'),
  (r'\b(enhance|enhancement|improve|boost|amplify|heighten|strengthen)\b|增强|提升|提高|强化', '⬆️'),
  (r'\b(equate|equation|equivalent|equal|compare|correspond)\b|等同|相等|对应|等价', '⚖️'),
  (r'\b(erode|erosion|wear away|corrode|undermine|weaken)\b|侵蚀|腐蚀|削弱|磨损', '🌊'),
  (r'\b(evaluate|evaluation|assess|appraise|judge|estimate|measure)\b|评估|评价|评判|衡量', '📊'),
  (r'\b(evident|evidence|proof|testimony|witness|demonstrate)\b|证据|证明|明显|证词|目击', '📜'),
  (r'\b(exceed|exceed|surpass|outdo|outstrip|go beyond|transcend)\b|超过|超出|超越|胜过', '📈'),
  (r'\b(exert|apply|exercise|wield|employ)\b|施加|运用|发挥|行使', '💪'),
  (r'\b(expenditure|expense|spending|cost|outlay|consumption)\b|支出|开支|花费|消耗', '💸'),
  (r'\b(exploit|exploitation|utilize|leverage|take advantage)\b|利用|开发|剥削|运用', '🛠️'),
  (r'\b(extensive|comprehensive|widespread|broad|far-reaching|exhaustive)\b|广泛|全面|大规模|详尽', '📚'),
  (r'\b(facilitate|facilitation|enable|promote|ease|accelerate)\b|促进|推动|便利|助长|简化', '⚡'),
  (r'\b(feature|characteristic|trait|attribute|aspect|quality)\b|特征|特点|特性|属性', '🏷️'),
  (r'\b(fluctuate|fluctuation|wave|vary|vacillate|swing|oscillate)\b|波动|起伏|变动|摇摆', '📈'),
  (r'\b(framework|structure|system|infrastructure|scaffold|setup)\b|框架|结构|体系|基础设施', '🏗️'),
  (r'\b(fundamental|essential|basic|core|underlying|primary)\b|基本|根本|核心|基础', '🧱'),
  (r'\b(generate|generation|produce|create|yield|bring about)\b|产生|生成|引起|创造', '⚙️'),
  (r'\b(hypothesis|theory|assumption|premise|supposition|postulate)\b|假设|假说|理论|前提|推测', '💡'),
  (r'\b(implement|implementation|execute|carry out|enforce|realize|realize)\b|实施|执行|落实|实现', '🛠️'),
  (r'\b(imply|implication|suggest|insinuate|entail|involve)\b|暗示|含义|意味着|涉及|牵连', '💭'),
  (r'\b(incentivize|encourage|motivate|promote|spur|drive)\b|激励|鼓励|驱动|推动', '🚀'),
  (r'\b(inclination|tendency|tend|disposition|propensity|lean|prefer)\b|倾向|趋势|偏好|意向', '🧭'),
  (r'\b(inevitable|unavoidable|certain|inescapable|bound to)\b|不可避免|必然|注定', '⏳'),
  (r'\b(inherent|intrinsic|innate|natural|innate|inborn)\b|固有|内在|天生|与生俱来', '🧬'),
  (r'\b(inhibit|inhibition|hinder|restrain|suppress|stifle|discourage)\b|抑制|阻碍|约束|妨碍', '⛔'),
  (r'\b(initiate|initiative|launch|begin|start|kick off|originate)\b|发起|启动|倡议|开创', '🚀'),
  (r'\b(innovate|innovation|creative|original|novel|breakthrough)\b|创新|革新|创意|原创|突破', '💡'),
  (r'\b(integral|essential|necessary|essential|vital|indispensable)\b|不可或缺|必要|必不可少', '🔗'),
  (r'\b(interpret|interpretation|read|understand|make sense|construe)\b|解读|理解|领会|阐释', '📖'),
  (r'\b(intricate|complicated|complex|elaborate|detailed|sophisticated)\b|错综复杂|复杂|精细|精巧', '🕸️'),
  (r'\b(intuition|intuitive|instinct|gut feeling|subconscious)\b|直觉|本能|潜意识', '🔮'),
  (r'\b(investigate|investigation|examine|probe|inquire|inspect|scrutinize)\b|调查|审查|探究|检查|查验', '🔍'),
  (r'\b(justify|justification|warrant|rationale|defend|explain)\b|证明|辩护|正当理由|解释', '⚖️'),
  (r'\b(legislate|legislation|make law|enact|pass|decree)\b|立法|制定法律|颁布|法令', '📜'),
  (r'\b(leverage|utilize|exploit|use|capitalize|benefit)\b|利用|杠杆|运用|获益', '⚖️'),
  (r'\b(manifest|manifestation|evident|show|demonstrate|reveal|display)\b|体现|表现|显现|证明', '👁️'),
  (r'\b(mechanism|process|method|system|procedure|apparatus)\b|机制|过程|方法|体系', '⚙️'),
  (r'\b(mitigate|mitigation|alleviate|lessen|reduce|ease|relieve)\b|缓解|减轻|缓和|降低', '💊'),
  (r'\b(norm|standard|criterion|benchmark|convention|rule)\b|规范|标准|准则|惯例', '📐'),
  (r'\b(notion|concept|idea|thought|belief|perception)\b|概念|观念|想法|看法', '💭'),
  (r'\b(obstacle|barrier|hurdle|impediment|blockage|hindrance)\b|障碍|阻碍|难关|屏障', '🚧'),
  (r'\b(optimum|optimal|ideal|best|perfect|most favorable)\b|最优|最佳|最理想|最适宜', '⭐'),
  (r'\b(paradigm|model|pattern|framework|example|prototype)\b|范式|模式|典范|范例|样板', '📐'),
  (r'\b(parameter|variable|factor|metric|limit|boundary)\b|参数|变量|要素|指标|界限', '🎚️'),
  (r'\b(phenomenon|event|occurrence|situation|trend|development)\b|现象|事件|形势|趋势', '🌠'),
  (r'\b(plausible|credible|believable|reasonable|feasible|sound)\b|貌似合理|可信|可行|合理', '🤷'),
  (r'\b(precede|preceding|prior|previous|former|earlier)\b|先于|在前|先前|较早', '⏪'),
  (r'\b(predominant|dominant|main|primary|principal|prevailing)\b|主导|主要|占优势|主流', '👑'),
  (r'\b(preliminary|initial|early|first|introductory|prior)\b|初步|最初|预备|先行', '1️⃣'),
  (r'\b(premise|assumption|proposition|basis|foundation)\b|前提|假设|基础|依据', '🏗️'),
  (r'\b(prescribe|prescription|recommend|direct|order|stipulate)\b|规定|开处方|指示|指定|推荐', '💊'),
  (r'\b(prevalent|widespread|common|widespread|current|pervasive)\b|流行|普遍|盛行|常见', '🌊'),
  (r'\b(profound|deep|intense|far-reaching|significant|meaningful)\b|深刻|深远|强烈|意义重大', '🌌'),
  (r'\b(prohibit|prohibition|ban|forbid|outlaw|restrict)\b|禁止|取缔|严禁|不准', '⛔'),
  (r'\b(prominent|famous|well-known|notable|distinguished|leading)\b|突出|著名|显要|杰出', '🌟'),
  (r'\b(prompt|prompt|trigger|elicit|initiate|induce|cause)\b|促使|引发|导致|引起', '⚡'),
  (r'\b(proportion|ratio|percentage|share|portion|extent)\b|比例|比率|份额|程度', '📊'),
  (r'\b(prospect|outlook|likelihood|expectation|future|chance)\b|前景|展望|可能性|机会', '🔭'),
  (r'\b(prudent|wise|sensible|judicious|cautious|careful)\b|谨慎|明智|审慎|稳妥', '🧠'),
  (r'\b(regulate|regulation|control|govern|manage|supervise|administer)\b|监管|调控|管理|规范|治理', '🎛️'),
  (r'\b(reinforce|strengthen|bolster|support|fortify|consolidate)\b|加强|强化|巩固|增援', '🧱'),
  (r'\b(relevant|relevance|pertinent|applicable|related|appropriate)\b|相关|切题|适用|恰当', '🔗'),
  (r'\b(reluctant|hesitant|unwilling|averse|resistant)\b|不情愿|勉强|迟疑|抗拒', '🙃'),
  (r'\b(remarkable|notable|extraordinary|striking|exceptional|impressive)\b|显著|非凡|引人注目|出色', '🌟'),
  (r'\b(resilient|resilience|tough|adaptable|robust|flexible)\b|有韧性|坚韧|适应力|抗压', '🌊'),
  (r'\b(retrieve|recover|fetch|regain|reclaim|restore)\b|取回|检索|恢复|找回', '📤'),
  (r'\b(scrutinize|scrutiny|examine|inspect|audit|review)\b|仔细检查|审查|审视|细察', '🔎'),
  (r'\b(sequence|order|series|succession|chain|arrangement)\b|顺序|序列|排列|次序', '🔢'),
  (r'\b(simultaneous|concurrent|at the same time|coincident)\b|同时|同步|并行', '⏱️'),
  (r'\b(sophisticated|advanced|complex|refined|high-tech|intricate)\b|精密|复杂|高级|尖端', '🛰️'),
  (r'\b(spectrum|range|gamut|variety|continuum)\b|范围|光谱|谱系|连续体', '🌈'),
  (r'\b(spontaneous|impromptu|voluntary|natural|automatic)\b|自发|即兴|自愿|自然', '🌀'),
  (r'\b(stimulate|stimulus|encourage|prompt|motivate|spur|provoke)\b|刺激|激励|促进|激发', '⚡'),
  (r'\b(strategy|strategic|plan|approach|tactic|policy)\b|策略|战略|计策|方针', '♟️'),
  (r'\b(substitute|replacement|alternative|replace|surrogate)\b|替代|取代|替代品', '🔄'),
  (r'\b(subtle|understated|delicate|fine|slight)\b|微妙|细微|精巧|隐约', '🪶'),
  (r'\b(sufficient|enough|adequate|ample|satisfactory)\b|足够|充分|充足|令人满意', '✅'),
  (r'\b(supplement|complement|addition|extra|adjunct)\b|补充|添加|附加|补充物', '➕'),
  (r'\b(surpass|exceed|outdo|outshine|transcend|outstrip)\b|超越|胜过|超过', '🏆'),
  (r'\b(susceptible|vulnerable|prone|sensitive|exposed)\b|易感|脆弱|易受|敏感', '🥀'),
  (r'\b(sustain|sustainable|maintain|support|uphold|persist)\b|维持|保持|支撑|坚持|可持续', '♻️'),
  (r'\b(tangible|concrete|physical|real|substantial)\b|有形|具体|切实|实体', '✋'),
  (r'\b(transparent|clear|open|obvious|blatant)\b|透明|公开|明显|坦率', '🔎'),
  (r'\b(undermine|weaken|sabotage|erode|impair|compromise)\b|削弱|破坏|损害|暗中破坏', '🕳️'),
  (r'\b(undertake|take on|embark|assume|pursue|commit)\b|承担|着手|开展|承诺|着手', '🎒'),
  (r'\b(utilize|use|employ|apply|exploit)\b|利用|使用|运用|应用', '🛠️'),
  (r'\b(validate|validation|verify|confirm|substantiate|authenticate)\b|验证|确认|证实|核准', '✅'),
  (r'\b(versatile|adaptable|flexible|all-round|multifaceted)\b|多才多艺|多面|灵活|通用', '🎭'),
  (r'\b(vivid|graphic|lively|striking|clear|picturesque)\b|生动|鲜明|逼真|鲜活', '🎨'),
  (r'\b(whereas|while|although|conversely|however)\b|然而|而|相反|尽管', '↔️'),
  # 补充：常见首字母触发不明确的用中文释义补
  (r'\b(carbon)\b|碳', '💨'),
  (r'\b(nitrogen|oxygen|hydrogen)\b|氮|氧|氢|气体', '🧪'),
  (r'\b(atom|molecule|particle|particle|electron|proton|nucleus)\b|原子|分子|粒子|电子|质子|原子核', '⚛️'),
  (r'\b(gravity|gravitational|magnetic|magnetism|electric|magnetic field)\b|重力|引力|磁性|磁|电磁', '🧲'),
  (r'\b(equator|latitude|longitude|hemisphere|tropic|tropic)\b|赤道|纬度|经度|半球', '🌐'),
  (r'\b(orbit|revolve|rotate|revolution|rotation|spin)\b|轨道|公转|自转|旋转|环绕', '🪐'),
  (r'\b(galaxy|universe|cosmos|cosmic|astronaut|spacecraft|space|planet)\b|星系|宇宙|太空|行星|航天|星际', '🌌'),
  (r'\b(geology|geological|mineral|rock formation|fossil|dinosaur)\b|地质|矿物|化石|恐龙|岩层', '🪨'),
  (r'\b(biology|biological|botany|zoology|species|organism|cell)\b|生物|植物学|动物学|物种|生物体|细胞', '🧬'),
  (r'\b(chemistry|chemical|compound|substance|reaction|element)\b|化学|化合物|物质|反应|元素', '⚗️'),
  (r'\b(physics|physical|mechanics|velocity|acceleration|momentum|force)\b|物理|力学|速度|加速度|动量', '⚛️'),
  (r'\b(mathematics|mathematical|geometry|equation|algebra|calculus|triangle)\b|数学|几何|方程|代数|微积分|三角', '📐'),
  (r'\b(statistics|statistical|probability|distribution|correlation|average|mean|median)\b|统计|概率|分布|相关|平均|中位数', '📊'),
]

# ---------- 词缀/词性大类兜底规则（多义词未命中时用）----------
AFFIX = [
  (r'(tion|sion|ment|ness|ity|ance|ence|ship|hood|age)$', '📦'),  # 抽象名词类
  (r'(er|or|ist|ian|eer)$', '🙋'),                                 # 人/从业者
  (r'ing$', '🟢'),                                                 # 进行
  (r'ed$', '🔙'),                                                  # 完成/过去
  (r'ly$', '✨'),                                                  # 副词
  (r'(ful|less|ous|able|ible|ive|al|ic)$', '🎨'),                  # 形容词
  (r'(ize|ise|ify|ate|en)$', '⚡'),                                # 动词化
]

def main():
    # 为每个词算出一个 emoji（词 -> emoji），只输出需要的
    # 但 wordEmoji 接收 (word, cn)，规则基于合并小写串
    pairs = []   # (regex, emoji)
    for pat, emo in SEMANTIC:
        pairs.append((re.compile(pat, re.I), emo))

    # 生成 JS：把规则写成 [ /regex/, 'emoji' ]
    js_lines = []
    for pat, emo in SEMANTIC:
        # 去重：避免 regex 重复
        js_lines.append(f"    [/{pat}/, '{emo}'],")
    # 默认兜底按词性（这里没法从 word 判断，用最通用的 📦）
    # 但把 wordEmoji 逻辑升级：先精配 map，再查 AFFIX，再默认

    out = '\n'.join(js_lines)
    print("SEMANTIC 规则数:", len(SEMANTIC))
    print("AFFIX 规则数:", len(AFFIX))
    # 保存规则到文件供后续注入
    with open(os.path.join(os.environ.get('TEMP','.'), 'emoji_rules.js'), 'w', encoding='utf-8') as f:
        f.write("var EMOJI_SEMANTIC=[\n"+out+"\n];\n")
        f.write("var EMOJI_AFFIX=[\n")
        for pat, emo in AFFIX:
            f.write(f"    [/{pat}/, '{emo}'],\n")
        f.write("];\n")
    print("已保存 TEMP/emoji_rules.js")

if __name__ == '__main__':
    main()
